Allow config files (and declare default values) for some modules

diff --git a/src/share/modules/background-nitrogen b/src/share/modules/background-nitrogen
--- a/src/share/modules/background-nitrogen
+++ b/src/share/modules/background-nitrogen
@@ -2,7 +2,23 @@
 
 # TODO: handle cases when $wallpaper_image, $wallpaper_mode or $wallpaper_bg_color is not set by the theme
 
-if [ -f "${THEMES_DIR}/${COLOR_THEME}/${wallpaper_image}" ]; then
+# read configuration from config file, if existing
+[ -f "${CONFIG_DIR}/modules/nitrogen" ] && source "${CONFIG_DIR}/modules/nitrogen"
+
+# declare default values
+NITROGEN_ENABLE_DEFAULT="true"
+
+# apply default values if appropriate
+NITROGEN_ENABLE="${NITROGEN_ENABLE:-${NITROGEN_ENABLE_DEFAULT}}"
+
+# perform operations if possible
+if ! [ "${NITROGEN_ENABLE}" == "true" ]; then
+    printf "* Not setting wallpaper with nitrogen (disabled from configuration).\n"
+    
+elif ! [ -f "${THEMES_DIR}/${COLOR_THEME}/${wallpaper_image}" ]; then
+    printf "* Not setting wallpaper with nitrogen (image file not found: ${THEMES_DIR}/${COLOR_THEME}/${wallpaper_image}).\n"
+    
+else
     printf "* Setting wallpaper with nitrogen..."
     case "${wallpaper_mode}" in
         centered)  nitrogen --save --set-centered "${THEMES_DIR}/${COLOR_THEME}/${wallpaper_image}" --set-color=${wallpaper_bg_color};;
diff --git a/src/share/modules/codeblocks b/src/share/modules/codeblocks
--- a/src/share/modules/codeblocks
+++ b/src/share/modules/codeblocks
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 # TODO: set bold font on some styles
-# TODO: set colors outside <colour_sets>
 
+# declare some constants
 CB_STYLE_CTR=0
 CB_PREFIX="/CodeBlocksConfig/editor/colour_sets"
 CB_COLORSET_NAME="gcs_theme"
@@ -12,8 +12,8 @@ CB_COLORSET_PREFIX="${CB_PREFIX}/${CB_COLORSET_NAME}"
 codeblocks_add_style() {
     
     if [ "$#" -ne 5 ]; then
-	    echo "Error: ${FUNCNAME[0]}() requires 5 arguments!"
-	    exit 2
+        echo "Error: ${FUNCNAME[0]}() requires 5 arguments!"
+        exit 2
     fi
     
     local name="$1"
@@ -27,7 +27,7 @@ codeblocks_add_style() {
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/NAME" --type elem -n "str" --value "${name}" "${file}"
     
     if [ "${fg_color}" != "default" ]; then
-	#xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE"
+    #xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE"
     #else
         local fg_red="$(   printf "%d" 0x${fg_color:1:2})"
         local fg_green="$( printf "%d" 0x${fg_color:3:2})"
@@ -41,7 +41,7 @@ codeblocks_add_style() {
     fi
     
     if [ "${bg_color}" != "default" ]; then
-	#xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"
+    #xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"
     #else
         local bg_red="$(   printf "%d" 0x${bg_color:1:2})"
         local bg_green="$( printf "%d" 0x${bg_color:3:2})"
@@ -57,11 +57,12 @@ codeblocks_add_style() {
     CB_STYLE_CTR="$(expr $CB_STYLE_CTR + 1)"
 }
 
+# helper function to set colors outside colorsets
 codeblocks_set_color (){
     
     if [ "$#" -ne 3 ]; then
-	    echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
-	    exit 2
+        echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
+        exit 2
     fi
     
     local path="$1"
@@ -75,12 +76,25 @@ codeblocks_set_color (){
     xmlstarlet ed --inplace --update "${path}/colour/@r" --value "${red}"   "${file}"
     xmlstarlet ed --inplace --update "${path}/colour/@g" --value "${green}" "${file}"
     xmlstarlet ed --inplace --update "${path}/colour/@b" --value "${blue}"  "${file}"
-    
 }
 
-CODEBLOCKS_CONFIG_FILE="$HOME/.codeblocks/default.conf"
 
-if [ -f "${CODEBLOCKS_CONFIG_FILE}" ]; then
+# declare default values
+CODEBLOCKS_ENABLE_DEFAULT="true"
+CODEBLOCKS_CONFIG_FILE_DEFAULT="$HOME/.codeblocks/default.conf"
+
+# apply default values if appropriate
+CODEBLOCKS_ENABLE="${CODEBLOCKS_ENABLE:-${CODEBLOCKS_ENABLE_DEFAULT}}"
+CODEBLOCKS_CONFIG_FILE="${CODEBLOCKS_CONFIG_FILE:-${CODEBLOCKS_CONFIG_FILE_DEFAULT}}"
+
+# perform operations if possible
+if ! [ "${CODEBLOCKS_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for Code::Blocks (disabled from configuration).\n"
+    
+elif ! [ -f "${CODEBLOCKS_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for Code::Blocks (target file not found: ${CODEBLOCKS_CONFIG_FILE}).\n"
+    
+else
     printf "* Setting colors for Code::Blocks..."
     
     # clear colorset with same name, if any
diff --git a/src/share/modules/terminator b/src/share/modules/terminator
--- a/src/share/modules/terminator
+++ b/src/share/modules/terminator
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+# helper function to set a value under the "default" section of terminator's config file
 terminator_set_value_default_profile() {
     
     local key="$1"
@@ -21,15 +22,29 @@ terminator_set_value_default_profile() {
         b loop
         : endloop
         }
-
     }
-
     " "${file}"
-    
-} 
+}
 
-TERMINATOR_CONFIG_FILE="$HOME/.config/terminator/config"
-if [ -f "${TERMINATOR_CONFIG_FILE}" ]; then
+# read configuration from config file, if existing
+[ -f "${CONFIG_DIR}/modules/terminator" ] && source "${CONFIG_DIR}/modules/terminator"
+
+# declare default values
+TERMINATOR_ENABLE_DEFAULT="true"
+TERMINATOR_CONFIG_FILE_DEFAULT="$HOME/.config/terminator/config"
+
+# apply default values if appropriate
+TERMINATOR_ENABLE="${TERMINATOR_ENABLE:-${TERMINATOR_ENABLE_DEFAULT}}"
+TERMINATOR_CONFIG_FILE="${TERMINATOR_CONFIG_FILE:-${TERMINATOR_CONFIG_FILE_DEFAULT}}"
+
+# perform operations if possible
+if ! [ "${TERMINATOR_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for terminator (disabled from configuration).\n"
+    
+elif ! [ -f "${TERMINATOR_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for terminator (target file not found: ${TERMINATOR_CONFIG_FILE}).\n"
+    
+else
     printf "* Setting colors for terminator..."
     terminator_set_value_default_profile "background_color" "${terminal_bg_color}"  "${TERMINATOR_CONFIG_FILE}"
     terminator_set_value_default_profile "foreground_color" "${terminal_fg_color}"  "${TERMINATOR_CONFIG_FILE}"
@@ -37,10 +52,10 @@ if [ -f "${TERMINATOR_CONFIG_FILE}" ]; then
     terminator_palette="${terminal_palette_black}:${terminal_palette_red}:${terminal_palette_green}:${terminal_palette_yellow}:${terminal_palette_blue}:${terminal_palette_purple}:${terminal_palette_cyan}:${terminal_palette_white}:${terminal_palette_light_black}:${terminal_palette_light_red}:${terminal_palette_light_green}:${terminal_palette_light_yellow}:${terminal_palette_light_blue}:${terminal_palette_light_purple}:${terminal_palette_light_cyan}:${terminal_palette_light_white}"
     terminator_set_value_default_profile "palette"          "${terminator_palette}" "${TERMINATOR_CONFIG_FILE}"
     if [ "${terminal_transparency}" != "" ]; then
-        terminator_set_value_default_profile "background_type"          "transparent" "${TERMINATOR_CONFIG_FILE}"
-        terminator_set_value_default_profile "background_darkness"          "${terminal_transparency}" "${TERMINATOR_CONFIG_FILE}"
+        terminator_set_value_default_profile "background_type"     "transparent"              "${TERMINATOR_CONFIG_FILE}"
+        terminator_set_value_default_profile "background_darkness" "${terminal_transparency}" "${TERMINATOR_CONFIG_FILE}"
     else
-        terminator_set_value_default_profile "background_type"          "solid" "${TERMINATOR_CONFIG_FILE}"
+        terminator_set_value_default_profile "background_type"     "solid"                    "${TERMINATOR_CONFIG_FILE}"
     fi
     printf " done.\n"
 fi
