Align sanity checks and configuration options among modules as much as possible

diff --git a/src/share/modules/cherrytree b/src/share/modules/cherrytree
--- a/src/share/modules/cherrytree
+++ b/src/share/modules/cherrytree
@@ -1,18 +1,29 @@
-#!/bin/sh
+#!/bin/bash
 
 which cherrytree >/dev/null || return
 
-: ${cherrytree_window_fg:=$text_color}
-: ${cherrytree_window_bg:=$base_color}
-: ${cherrytree_tree_fg:=$text_color}
-: ${cherrytree_tree_bg:=$base_color}
-: ${cherrytree_link_web:=$link_color}
-: ${cherrytree_link_node:=$link_color}
-: ${cherrytree_link_file:=$link_color}
-: ${cherrytree_link_directory:=$link_color}
+: ${cherrytree_window_fg:=${text_color}}
+: ${cherrytree_window_bg:=${base_color}}
+: ${cherrytree_tree_fg:=${text_color}}
+: ${cherrytree_tree_bg:=${base_color}}
+: ${cherrytree_link_web:=${link_color}}
+: ${cherrytree_link_node:=${link_color}}
+: ${cherrytree_link_file:=${link_color}}
+: ${cherrytree_link_directory:=${link_color}}
 
-CHERRYTREE_CONFIG_FILE="$HOME/.config/cherrytree/config.cfg"
-if [ -f "${CHERRYTREE_CONFIG_FILE}" ]; then
+CHERRYTREE_ENABLE_DEFAULT="true"
+CHERRYTREE_CONFIG_FILE_DEFAULT="$HOME/.config/cherrytree/config.cfg"
+
+CHERRYTREE_ENABLE="$(crudini      --get ${CONFIG_FILE} cherrytree enable      2>/dev/null || echo "${CHERRYTREE_ENABLE_DEFAULT}")"
+CHERRYTREE_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} cherrytree config_file 2>/dev/null || echo "${CHERRYTREE_CONFIG_FILE_DEFAULT}")"
+
+if ! [ "${CHERRYTREE_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for cherrytree (disabled from configuration).\n"
+
+elif ! [ -f "${CHERRYTREE_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for cherrytree (configuration file ${CHERRYTREE_CONFIG_FILE} not found).\n"
+
+else
     printf "* Setting colors for cherrytree..."
     set_value "rt_def_fg"     " = " "${cherrytree_window_fg}"      "${CHERRYTREE_CONFIG_FILE}"
     set_value "rt_def_bg"     " = " "${cherrytree_window_bg}"      "${CHERRYTREE_CONFIG_FILE}"
@@ -23,6 +34,4 @@ if [ -f "${CHERRYTREE_CONFIG_FILE}" ]; then
     set_value "col_link_file" " = " "${cherrytree_link_file}"      "${CHERRYTREE_CONFIG_FILE}"
     set_value "col_link_fold" " = " "${cherrytree_link_directory}" "${CHERRYTREE_CONFIG_FILE}"
     printf " done.\n"
-else
-    printf "* Not setting colors for cherrytree (configuration file ${CHERRYTREE_CONFIG_FILE} not found).\n"
 fi
diff --git a/src/share/modules/codeblocks b/src/share/modules/codeblocks
--- a/src/share/modules/codeblocks
+++ b/src/share/modules/codeblocks
@@ -12,25 +12,23 @@ CB_COLORSET_PREFIX="${CB_PREFIX}/${CB_COLORSET_NAME}"
 
 # helper function to set styles in Code::blocks config file
 codeblocks_add_style() {
-    
+
     if [ "$#" -ne 5 ]; then
         echo "Error: ${FUNCNAME[0]}() requires 5 arguments!"
         exit 2
     fi
-    
+
     local name="$1"
     local lang="$2"
     local fg_color="$3"
     local bg_color="$4"
     local file="$5"
-    
+
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}"                           --type elem -n "style${CB_STYLE_CTR}"  "${file}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"      --type elem -n "NAME"                  "${file}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/NAME" --type elem -n "str" --value "${name}" "${file}"
-    
+
     if [ "${fg_color}" != "default" ]; then
-    #xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE"
-    #else
         local fg_red="$(   printf "%d" 0x${fg_color:1:2})"
         local fg_green="$( printf "%d" 0x${fg_color:3:2})"
         local fg_blue="$(  printf "%d" 0x${fg_color:5:2})"
@@ -41,7 +39,7 @@ codeblocks_add_style() {
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "g"      --value "${fg_green}" "${file}"
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "b"      --value "${fg_blue}"  "${file}"
     fi
-    
+
     if [ "${bg_color}" != "default" ]; then
     #xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"
     #else
@@ -55,74 +53,70 @@ codeblocks_add_style() {
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "g"      --value "${bg_green}" "${file}"
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "b"      --value "${bg_blue}"  "${file}"
     fi
-    
+
     CB_STYLE_CTR="$(expr $CB_STYLE_CTR + 1)"
 }
 
 # helper function to set colors outside colorsets
 codeblocks_set_color (){
-    
+
     if [ "$#" -ne 3 ]; then
         echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
         exit 2
     fi
-    
+
     local path="$1"
     local color="$2"
     local file="$3"
-    
+
     local red="$(   printf "%d" 0x${color:1:2})"
     local green="$( printf "%d" 0x${color:3:2})"
     local blue="$(  printf "%d" 0x${color:5:2})"
-    
+
     xmlstarlet ed --inplace --update "${path}/colour/@r" --value "${red}"   "${file}"
     xmlstarlet ed --inplace --update "${path}/colour/@g" --value "${green}" "${file}"
     xmlstarlet ed --inplace --update "${path}/colour/@b" --value "${blue}"  "${file}"
 }
 
-
-# declare default values
 CODEBLOCKS_ENABLE_DEFAULT="true"
 CODEBLOCKS_CONFIG_FILE_DEFAULT="$HOME/.config/codeblocks/default.conf"
 
-# apply default values if appropriate
-CODEBLOCKS_ENABLE="${CODEBLOCKS_ENABLE:-${CODEBLOCKS_ENABLE_DEFAULT}}"
-CODEBLOCKS_CONFIG_FILE="${CODEBLOCKS_CONFIG_FILE:-${CODEBLOCKS_CONFIG_FILE_DEFAULT}}"
+CODEBLOCKS_ENABLE="$(crudini      --get ${CONFIG_FILE} codeblocks enable      2>/dev/null || echo "${CODEBLOCKS_ENABLE_DEFAULT}")"
+CODEBLOCKS_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} codeblocks config_file 2>/dev/null || echo "${CODEBLOCKS_CONFIG_FILE_DEFAULT}")"
 
-# perform operations if possible
 if ! [ "${CODEBLOCKS_ENABLE}" == "true" ]; then
     printf "* Not setting colors for Code::Blocks (disabled from configuration).\n"
-    
+
 elif ! [ -f "${CODEBLOCKS_CONFIG_FILE}" ]; then
-    printf "* Not setting colors for Code::Blocks (target file not found: ${CODEBLOCKS_CONFIG_FILE}).\n"
-    
+    printf "* Not setting colors for Code::Blocks (configuration file not found: ${CODEBLOCKS_CONFIG_FILE}).\n"
+
 elif [ "${editor_syntax_enable}" == "false" ]; then
     if [ "$(xmlstarlet sel -t -v "${CB_PREFIX}/ACTIVE_COLOUR_SET/str" "${CODEBLOCKS_CONFIG_FILE}")" == "${CB_COLORSET_NAME}" ]; then
         # set default colorset as active
         xmlstarlet ed --inplace --update "${CB_PREFIX}/ACTIVE_COLOUR_SET/str" --value "default" "${CODEBLOCKS_CONFIG_FILE}"
     fi
-    
+
 else
     printf "* Setting colors for Code::Blocks..."
-    
+
     # clear colorset with same name, if any
     xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}"                                                             "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     # create new colorset
     xmlstarlet ed --inplace --subnode "${CB_PREFIX}"                  --type elem -n "${CB_COLORSET_NAME}"               "${CODEBLOCKS_CONFIG_FILE}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}"         --type elem -n "NAME"                              "${CODEBLOCKS_CONFIG_FILE}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/NAME"    --type elem -n "str" --value "${CB_COLORSET_NAME}" "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     # apply C/C++ syntax highlighting
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}"         --type elem -n "cc"                                "${CODEBLOCKS_CONFIG_FILE}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/cc"      --type elem -n "NAME"                              "${CODEBLOCKS_CONFIG_FILE}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/cc/NAME" --type elem -n "str" --value "C/C++"               "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     CB_STYLE_CTR=0
-    
+
     codeblocks_add_style "Default"   "cc" "${editor_fg}"          "${editor_bg}"          "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Selection" "cc" "${editor_selected_fg}" "${editor_selected_bg}" "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     codeblocks_add_style "Number"                                "cc" "${editor_number}"          "default"      "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "User keyword"                          "cc" "${editor_class}"           "default"      "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "String"                                "cc" "${editor_string}"          "default"      "${CODEBLOCKS_CONFIG_FILE}"
@@ -137,16 +131,16 @@ else
     codeblocks_add_style "Character"                             "cc" "${editor_character}"       "default"      "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Preprocessor"                          "cc" "${editor_preprocessor}"    "default"      "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Matching brace highlight"              "cc" "${editor_brace_good}"      "${editor_bg}" "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     codeblocks_add_style "Active line"                           "cc" "default" "${editor_current_line_bg}" "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     # apply diff/patch syntax highlighting
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}"                --type elem -n "diffpatch"                "${CODEBLOCKS_CONFIG_FILE}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/diffpatch"      --type elem -n "NAME"                     "${CODEBLOCKS_CONFIG_FILE}"
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/diffpatch/NAME" --type elem -n "str" --value "Diff/Patch" "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     CB_STYLE_CTR=0
-    
+
     codeblocks_add_style "Default"  "diffpatch" "${editor_fg}"           "${editor_bg}" "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Comment"  "diffpatch" "${editor_comment}"      "default"      "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Command"  "diffpatch" "${editor_keyword}"      "default"      "${CODEBLOCKS_CONFIG_FILE}"
@@ -154,10 +148,10 @@ else
     codeblocks_add_style "Position" "diffpatch" "${editor_number}"       "default"      "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Deleted"  "diffpatch" "${editor_diff_removed}" "default"      "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Added"    "diffpatch" "${editor_diff_added}"   "default"      "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     # set new colorset as active
     xmlstarlet ed --inplace --update "${CB_PREFIX}/ACTIVE_COLOUR_SET/str" --value "${CB_COLORSET_NAME}" "${CODEBLOCKS_CONFIG_FILE}"
-    
+
     codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/ACTIVE_CAPTION_COLOUR"            "${titlebar_focused_bg_color}"   "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/ACTIVE_CAPTION_GRADIENT_COLOUR"   "${titlebar_focused_bg_color}"   "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/ACTIVE_CAPTION_TEXT_COLOUR"       "${titlebar_focused_fg_color}"   "${CODEBLOCKS_CONFIG_FILE}"
@@ -165,15 +159,12 @@ else
     codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/INACTIVE_CAPTION_GRADIENT_COLOUR" "${titlebar_unfocused_bg_color}" "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/INACTIVE_CAPTION_TEXT_COLOUR"     "${titlebar_unfocused_fg_color}" "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/PROJECT_TREE_NON_SOURCE_FILES"    "${editor_comment}"              "${CODEBLOCKS_CONFIG_FILE}"
-    
-    
+
     codeblocks_set_color "/CodeBlocksConfig/colours/list/EDITOR_MARGIN_CHROME"           "${bg_color}"                "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/colours/list/EDITOR_MARGIN_CHROME_HIGHLIGHT" "${bg_color}"                "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/colours/list/EDITOR_LINENUMBERS_BG"          "${bg_color}"                "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/colours/list/EDITOR_LINENUMBERS_FG"          "${fg_color}"                "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_set_color "/CodeBlocksConfig/colours/list/EDITOR_GUTTER"                  "${editor_long_line_marker}" "${CODEBLOCKS_CONFIG_FILE}"
-    
-    
-    
+
     printf " done.\n"
 fi
diff --git a/src/share/modules/conky b/src/share/modules/conky
--- a/src/share/modules/conky
+++ b/src/share/modules/conky
@@ -6,27 +6,37 @@
 
 which conky >/dev/null || return
 
-CONKY_CONFIG_FILES=$(crudini --get ${CONFIG_FILE} conky config_files 2>/dev/null || echo "${HOME}/.conkyrc")
-eval conky_color0=$(crudini --get ${CONFIG_FILE} conky color0 2>/dev/null || echo ${text_color} )
-CONKY_RESTART_COMMAND=$(crudini --get ${CONFIG_FILE} conky restart_command 2>/dev/null || echo )
+CONKY_ENABLE_DEFAULT="true"
+CONKY_ENABLE="$(crudini --get ${CONFIG_FILE} conky enable 2>/dev/null || echo "${CONKY_ENABLE_DEFAULT}")"
+CONKY_RESTART_COMMAND_DEFAULT=""
 
-printf "* Setting colors for conky...\n"
-for i in ${CONKY_CONFIG_FILES}; do
-    
-    file="$i"
-    if [ ${file:0:1} == \" ]; then
-        file=${file:1}
-    fi
-    if [ ${file: -1} == \" ]; then
-        file=${file:0:-1}
-    fi
-    
-    if [ -f "${file}" ]; then
+CONKY_CONFIG_FILES="$(crudini    --get ${CONFIG_FILE} conky config_files    2>/dev/null || echo "${HOME}/.conkyrc")"
+eval conky_color0="$(crudini     --get ${CONFIG_FILE} conky color0          2>/dev/null || echo "${text_color}" )"
+CONKY_RESTART_COMMAND="$(crudini --get ${CONFIG_FILE} conky restart_command 2>/dev/null || echo "${CONKY_RESTART_COMMAND_DEFAULT}")"
+
+if ! [ "${CONKY_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for conky (disabled from configuration).\n"
+else
+    printf "* Setting colors for conky...\n"
+    for i in ${CONKY_CONFIG_FILES}; do
+        
+        file="$i"
+        if [ ${file:0:1} == \" ]; then
+            file=${file:1}
+        fi
+        if [ ${file: -1} == \" ]; then
+            file=${file:0:-1}
+        fi
+
         printf "  ${file}..."
-        set_value "default_color" " "  "${text_color:1}" "${file}"
-        set_value "color0" " " "${conky_color0:1}" "${file}"
-        printf " done.\n"
-    fi
-done
+        if [ -f "${file}" ]; then
+            set_value "default_color" " "  "${text_color:1}" "${file}"
+            set_value "color0" " " "${conky_color0:1}" "${file}"
+            printf " done.\n"
+        else
+            printf "not found!\n"
+        fi
+    done
 
-$CONKY_RESTART_COMMAND &>/dev/null
+    $CONKY_RESTART_COMMAND &>/dev/null
+fi
diff --git a/src/share/modules/dmenu b/src/share/modules/dmenu
--- a/src/share/modules/dmenu
+++ b/src/share/modules/dmenu
@@ -16,11 +16,23 @@
 # therefore I'm settings colors there
 
 which dmenu >/dev/null || return
+which i3 >/dev/null || return
 
-DMENU_RESTART_COMMAND=$(crudini --get ${CONFIG_FILE} dmenu restart_command 2>/dev/null || echo )
+DMENU_ENABLE_DEFAULT="false"
+I3_CONFIG_FILE_DEFAULT="$HOME/.config/i3/config"
+DMENU_RESTART_COMMAND_DEFAULT=""
 
-I3_CONFIG_FILE="$HOME/.config/i3/config"
-if [ -f "${I3_CONFIG_FILE}" ]; then
+DMENU_ENABLE="$(crudini --get ${CONFIG_FILE} dmenu enable 2>/dev/null || echo "${DMENU_ENABLE_DEFAULT}")"
+I3_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} i3wm config_file 2>/dev/null || echo "${I3_CONFIG_FILE_DEFAULT}")"
+DMENU_RESTART_COMMAND="$(crudini --get ${CONFIG_FILE} dmenu restart_command 2>/dev/null || echo "${DMENU_RESTART_COMMAND_DEFAULT}")"
+
+if ! [ "${DMENU_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for dmenu (disabled from configuration).\n"
+
+elif ! [ -f "${I3_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for dmenu (configuration file \"${I3_CONFIG_FILE}\" not found).\n"
+
+else
     printf "* Setting colors for dmenu..."
     set_value 'set \$dmenu_normal_bg'   " " "${tray_bg}"         "${I3_CONFIG_FILE}"
     set_value 'set \$dmenu_normal_fg'   " " "${tray_fg}"         "${I3_CONFIG_FILE}"
diff --git a/src/share/modules/dunst b/src/share/modules/dunst
--- a/src/share/modules/dunst
+++ b/src/share/modules/dunst
@@ -1,11 +1,14 @@
-#!/bin/sh
+#!/bin/bash
 
 which dunst >/dev/null || return
 
-DUNST_RESTART_COMMAND=$(crudini --get ${CONFIG_FILE} dunst restart_command 2>/dev/null || echo )
-
+DUNST_ENABLE_DEFAULT="true"
 DUNST_CONFIG_FILE_DEFAULT="$HOME/.config/dunst/dunstrc"
-DUNST_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} dunst config_file 2>/dev/null || echo "${DUNST_CONFIG_FILE_DEFAULT}")"
+DUNST_RESTART_COMMAND_DEFAULT=""
+
+DUNST_ENABLE="$(crudini          --get ${CONFIG_FILE} dunst enable          2>/dev/null || echo "${DUNST_ENABLE_DEFAULT}")"
+DUNST_CONFIG_FILE="$(crudini     --get ${CONFIG_FILE} dunst config_file     2>/dev/null || echo "${DUNST_CONFIG_FILE_DEFAULT}")"
+DUNST_RESTART_COMMAND="$(crudini --get ${CONFIG_FILE} dunst restart_command 2>/dev/null || echo "${DUNST_RESTART_COMMAND_DEFAULT}")"
 
 : ${dunst_frame:=${notification_frame}}
 : ${dunst_urgency_low_bg:=${notification_low_bg}}
@@ -15,7 +18,13 @@ DUNST_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} dunst config_file 2>/dev/null 
 : ${dunst_urgency_critical_bg:=${notification_high_bg}}
 : ${dunst_urgency_critical_fg:=${notification_high_fg}}
 
-if [ -f "${DUNST_CONFIG_FILE}" ]; then
+if ! [ "${DUNST_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for dunst (disabled from configuration).\n"
+
+elif ! [ -f "${DUNST_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for dunst (configuration file \"${DUNST_CONFIG_FILE}\" not found).\n"
+
+else
     printf "* Setting colors for dunst..."
     set_value_section "frame"            "color"      " = " "\"${dunst_frame}\""               "${DUNST_CONFIG_FILE}"
     set_value_section "urgency_low"      "background" " = " "\"${dunst_urgency_low_bg}\""      "${DUNST_CONFIG_FILE}"
@@ -26,6 +35,4 @@ if [ -f "${DUNST_CONFIG_FILE}" ]; then
     set_value_section "urgency_critical" "foreground" " = " "\"${dunst_urgency_critical_fg}\"" "${DUNST_CONFIG_FILE}"
     $DUNST_RESTART_COMMAND &>/dev/null
     printf " done.\n"
-else
-    printf "* Not setting colors for dunst (config file \"${DUNST_CONFIG_FILE}\" not found).\n"
 fi
diff --git a/src/share/modules/galculator b/src/share/modules/galculator
--- a/src/share/modules/galculator
+++ b/src/share/modules/galculator
@@ -8,18 +8,26 @@ which galculator >/dev/null || return
 : ${galculator_module_active_color:=${selected_bg_color}}
 : ${galculator_module_inactive_color:=${unfocused_text_color}}
 
-GALCULATOR_CONFIG_FILE="$HOME/.config/galculator/galculator.conf"
-if [ -f "${GALCULATOR_CONFIG_FILE}" ]; then
+GALCULATOR_ENABLE_DEFAULT="true"
+GALCULATOR_CONFIG_FILE_DEFAULT="$HOME/.config/galculator/galculator.conf"
 
+GALCULATOR_ENABLE="$(crudini      --get ${CONFIG_FILE} galculator enable      2>/dev/null || echo "${GALCULATOR_ENABLE_DEFAULT}")"
+GALCULATOR_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} galculator config_file 2>/dev/null || echo "${GALCULATOR_CONFIG_FILE_DEFAULT}")"
+
+if ! [ "${GALCULATOR_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for Galculator (disabled from configuration).\n"
+
+elif ! [ -f "${GALCULATOR_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for Galculator (config file \"${GALCULATOR_CONFIG_FILE}\" not found).\n"
+
+else
     printf "* Setting colors for Galculator..."
-    
+
     set_value "display_bkg_color"             "=" "\"${galculator_bg_color}\""              "${GALCULATOR_CONFIG_FILE}"
     set_value "display_result_color"          "=" "\"${galculator_result_color}\""          "${GALCULATOR_CONFIG_FILE}"
     set_value "display_stack_color"           "=" "\"${galculator_stack_color}\""           "${GALCULATOR_CONFIG_FILE}"
     set_value "display_module_active_color"   "=" "\"${galculator_module_active_color}\""   "${GALCULATOR_CONFIG_FILE}"
     set_value "display_module_inactive_color" "=" "\"${galculator_module_inactive_color}\"" "${GALCULATOR_CONFIG_FILE}"
-    
+
     printf " done.\n"
-else
-    printf "* Not setting colors for Galculator (config file \"${GALCULATOR_CONFIG_FILE}\" not found).\n"
 fi
diff --git a/src/share/modules/geany b/src/share/modules/geany
--- a/src/share/modules/geany
+++ b/src/share/modules/geany
@@ -2,21 +2,34 @@
 
 which geany >/dev/null || return
 
-GEANY_CONFIG_FILE="$HOME/.config/geany/geany.conf"
-if [ "${editor_syntax_enable}" == "false" ]; then
+GEANY_ENABLE_DEFAULT="true"
+GEANY_CONFIG_FILE_DEFAULT="$HOME/.config/geany/geany.conf"
+
+GEANY_ENABLE="$(crudini      --get ${CONFIG_FILE} geany enable      2>/dev/null || echo "${GEANY_ENABLE_DEFAULT}")"
+GEANY_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} geany config_file 2>/dev/null || echo "${GEANY_CONFIG_FILE_DEFAULT}")"
+
+if ! [ "${GEANY_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for Geany (disabled from configuration).\n"
+
+elif [ "${editor_syntax_enable}" == "false" ]; then
     if [ "$(crudini --get $HOME/.config/geany/geany.conf geany color_scheme)" == "gcs.conf" ]; then
         set_value "color_scheme" "=" ""                    "${GEANY_CONFIG_FILE}"
     fi
     set_value "colour_fore"  "=" "${terminal_fg_color}" "${GEANY_CONFIG_FILE}"
     set_value "colour_back"  "=" "${terminal_bg_color}" "${GEANY_CONFIG_FILE}"
 
-elif [ -f "${GEANY_CONFIG_FILE}" ]; then
+elif ! [ -f "${GEANY_CONFIG_FILE}" ]; then
+    printf "* Not settin colors for Geany (configuration file \"${GEANY_CONFIG_FILE}\" not found).\n"
+
+else
     printf "* Setting colors for Geany..."
+    geany_template_file="${BASH_SOURCE%/*}/geany-template.conf"
     
-    if [ -f "${BASH_SOURCE%/*}/geany-template.conf" ]; then
+    if [ -f "${geany_template_file}" ]; then
         [ -d "$HOME/.config/geany/colorschemes" ] || mkdir "$HOME/.config/geany/colorschemes"
+        mkdir -p "$HOME/.config/geany/colorschemes"
         destfile="$HOME/.config/geany/colorschemes/gcs.conf"
-        cp "${BASH_SOURCE%/*}/geany-template.conf" "${destfile}"
+        cp "${geany_template_file}" "${destfile}"
 
         set_value "editor_bg"              "=" "${editor_bg}"              "${destfile}"
         set_value "editor_fg"              "=" "${editor_fg}"              "${destfile}"
@@ -52,7 +65,7 @@ elif [ -f "${GEANY_CONFIG_FILE}" ]; then
 
         printf " done.\n" 
     else
-        printf " error: template not found!\n"
+        printf " error: template file \"${geany_template_file}\" not found!\n"
     fi
 
 fi
diff --git a/src/share/modules/gpicview b/src/share/modules/gpicview
--- a/src/share/modules/gpicview
+++ b/src/share/modules/gpicview
@@ -1,9 +1,20 @@
-#!/bin/sh
+#!/bin/bash
 
 which gpicview >/dev/null || return
 
-GPICVIEW_CONFIG_FILE="$HOME/.config/gpicview/gpicview.conf"
-if [ -f "${GPICVIEW_CONFIG_FILE}" ]; then
+GPICVIEW_ENABLE_DEFAULT="true"
+GPICVIEW_CONFIG_FILE_DEFAULT="$HOME/.config/gpicview/gpicview.conf"
+
+GPICVIEW_ENABLE="$(crudini      --get ${CONFIG_FILE} gpicview enable      2>/dev/null || echo "${GPICVIEW_ENABLE_DEFAULT}")"
+GPICVIEW_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} gpicview config_file 2>/dev/null || echo "${GPICVIEW_CONFIG_FILE_DEFAULT}")"
+
+if ! [ "${GPICVIEW_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for gpicview (disabled from configuration).\n"
+
+elif ! [ -f "${GPICVIEW_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for gpicview (configuration file \"${GPICVIEW_CONFIG_FILE}\" not found).\n"
+
+else
     printf "* Setting colors for gpicview..."
     set_value "bg"      "=" "${base_color}" "${GPICVIEW_CONFIG_FILE}"
     set_value "bg_full" "=" "${base_color}" "${GPICVIEW_CONFIG_FILE}"
diff --git a/src/share/modules/lxterminal b/src/share/modules/lxterminal
--- a/src/share/modules/lxterminal
+++ b/src/share/modules/lxterminal
@@ -2,8 +2,19 @@
 
 which lxterminal >/dev/null || return
 
-LXTERMINAL_CONFIG_FILE="$HOME/config/lxterminal/lxterminal.conf"
-if [ -f "${LXTERMINAL_CONFIG_FILE}" ]; then
+LXTERMINAL_ENABLE_DEFAULT="true"
+LXTERMINAL_CONFIG_FILE_DEFAULT="$HOME/config/lxterminal/lxterminal.conf"
+
+LXTERMINAL_ENABLE="$(crudini      --get ${CONFIG_FILE} lxterminal enable      2>/dev/null || echo "${LXTERMINAL_ENABLE_DEFAULT}")"
+LXTERMINAL_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} lxterminal config_file 2>/dev/null || echo "${LXTERMINAL_CONFIG_FILE_DEFAULT}")"
+
+if ! [ "${LXTERMINAL_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for LXTerminal (disabled from configuration).\n"
+
+elif ! [ -f "${LXTERMINAL_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for LXTerminal (configuration file \"${LXTERMINAL_CONFIG_FILE}\" not found).\n"
+
+else
     printf "* Setting colors for LXTerminal..."
     set_value "bgcolor" "=" "${terminal_bg_color}" "${LXTERMINAL_CONFIG_FILE}"
     set_value "fgcolor" "=" "${terminal_fg_color}" "${LXTERMINAL_CONFIG_FILE}"
diff --git a/src/share/modules/mcomix b/src/share/modules/mcomix
--- a/src/share/modules/mcomix
+++ b/src/share/modules/mcomix
@@ -30,9 +30,19 @@ set_color_mcomix() {
     " "${file}"
 }
 
-MCOMIX_CONFIG_FILE="$HOME/.config/mcomix/preferences.conf"
+MCOMIX_ENABLE_DEFAULT="true"
+MCOMIX_CONFIG_FILE_DEFAULT="$HOME/.config/mcomix/preferences.conf"
 
-if [ -f "${MCOMIX_CONFIG_FILE}" ]; then
+MCOMIX_ENABLE="$(crudini      --get ${CONFIG_FILE} mcomix enable      2>/dev/null || echo "${MCOMIX_ENABLE_DEFAULT}")"
+MCOMIX_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} mcomix config_file 2>/dev/null || echo "${MCOMIX_CONFIG_FILE_DEFAULT}")"
+
+if ! [ "${MCOMIX_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for MComix (disabled from configuration).\n"
+
+elif ! [ -f "${MCOMIX_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for MComix (configuration file \"${MCOMIX_CONFIG_FILE}\" not found).\n"
+
+else
     printf "* Setting colors for MComix..."
     set_color_mcomix "bg colour"       "${base_color}" "${MCOMIX_CONFIG_FILE}"
     set_color_mcomix "thumb bg colour" "${bg_color}"   "${MCOMIX_CONFIG_FILE}"
diff --git a/src/share/modules/octave b/src/share/modules/octave
--- a/src/share/modules/octave
+++ b/src/share/modules/octave
@@ -4,9 +4,16 @@
 
 which octave >/dev/null || return
 
-OCTAVE_CONFIG_FILE="$HOME/.config/octave/qt-settings"
+OCTAVE_ENABLE_DEFAULT="true"
+OCTAVE_CONFIG_FILE_DEFAULT="$HOME/.config/octave/qt-settings"
 
-if [ "${editor_syntax_enable}" == "false" ]; then
+OCTAVE_ENABLE="$(crudini      --get ${CONFIG_FILE} octave enable      2>/dev/null || echo "${OCTAVE_ENABLE_DEFAULT}")"
+OCTAVE_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} octave config_file 2>/dev/null || echo "${OCTAVE_CONFIG_FILE_DEFAULT}")"
+
+if ! [ "${OCTAVE_ENABLE}" == "true" ]; then
+    printf "* Not setting colors for Octave (disabled from configuration).\n"
+
+elif [ "${editor_syntax_enable}" == "false" ]; then
     if [ -f "${OCTAVE_CONFIG_FILE}" ]; then
         crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_b" "${terminal_bg_color}"
         crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_f" "${terminal_fg_color}"
@@ -45,17 +52,19 @@ if [ "${editor_syntax_enable}" == "false" ]; then
     set_value "Octave\\\\style8\\\\color" "=" "$(printf "%d" 0xFFAA00)" "${OCTAVE_CONFIG_FILE}"
     set_value "Octave\\\\style8\\\\paper" "=" "$(printf "%d" 0xFFFFFF)" "${OCTAVE_CONFIG_FILE}"
 
-elif [ -f "${OCTAVE_CONFIG_FILE}" ]; then
+elif ! [ -f "${OCTAVE_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for Octave (configuration \"${OCTAVE_CONFIG_FILE}\" not found).\n"
 
+else
     printf "* Setting colors for Octave..."
-    
+
     crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_b" "${terminal_bg_color}"
     crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_f" "${terminal_fg_color}"
     crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_s" "${selected_bg_color}"
     crudini --set "${OCTAVE_CONFIG_FILE}" "terminal" "color_c" "${terminal_fg_color}"
-    
+
     crudini --set "${OCTAVE_CONFIG_FILE}" "editor" "highlight_current_line_color" "${editor_current_line_bg}"
-    
+
     # TODO: obseve these in practice
     crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_a" "${editor_class}"
     crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_f" "${editor_number}"
@@ -63,7 +72,7 @@ elif [ -f "${OCTAVE_CONFIG_FILE}" ]; then
     crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_h" "${editor_operator}"
     crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_i" "${editor_string}"
     crudini --set "${OCTAVE_CONFIG_FILE}" "workspaceview" "color_p" "${editor_preprocessor}"
-    
+
     set_value "Octave\\\\defaultcolor"    "=" "$(printf   "%d" 0x${editor_fg:1:6})"       "${OCTAVE_CONFIG_FILE}"
     set_value "Octave\\\\defaultpaper"    "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
     set_value "Octave\\\\style0\\\\color" "=" "$(printf   "%d" 0x${editor_fg:1:6})"       "${OCTAVE_CONFIG_FILE}"
@@ -86,5 +95,4 @@ elif [ -f "${OCTAVE_CONFIG_FILE}" ]; then
     set_value "Octave\\\\style8\\\\paper" "=" "$(printf   "%d" 0x${editor_bg:1:6})"       "${OCTAVE_CONFIG_FILE}"
 
     printf " done.\n"
-
 fi
diff --git a/src/share/modules/terminator b/src/share/modules/terminator
--- a/src/share/modules/terminator
+++ b/src/share/modules/terminator
@@ -1,14 +1,14 @@
-#!/bin/sh
+#!/bin/bash
 
 which terminator >/dev/null || return
 
 # helper function to set a value under the "default" section of terminator's config file
 terminator_set_value_default_profile() {
-    
+
     local key="$1"
     local value="$2"
     local file="$3"
-    
+
     sed -i "
     /\[profiles\]/{
     N
@@ -28,24 +28,18 @@ terminator_set_value_default_profile() {
     " "${file}"
 }
 
-# read configuration from config file, if existing
-[ -f "${CONFIG_DIR}/modules/terminator" ] && source "${CONFIG_DIR}/modules/terminator"
-
-# declare default values
 TERMINATOR_ENABLE_DEFAULT="true"
 TERMINATOR_CONFIG_FILE_DEFAULT="$HOME/.config/terminator/config"
 
-# apply default values if appropriate
-TERMINATOR_ENABLE="${TERMINATOR_ENABLE:-${TERMINATOR_ENABLE_DEFAULT}}"
-TERMINATOR_CONFIG_FILE="${TERMINATOR_CONFIG_FILE:-${TERMINATOR_CONFIG_FILE_DEFAULT}}"
+TERMINATOR_ENABLE="$(crudini      --get ${CONFIG_FILE} terminator enable      2>/dev/null || echo "${TERMINATOR_ENABLE_DEFAULT}")"
+TERMINATOR_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} terminator config_file 2>/dev/null || echo "${TERMINATOR_CONFIG_FILE_DEFAULT}")"
 
-# perform operations if possible
 if ! [ "${TERMINATOR_ENABLE}" == "true" ]; then
     printf "* Not setting colors for terminator (disabled from configuration).\n"
-    
+
 elif ! [ -f "${TERMINATOR_CONFIG_FILE}" ]; then
-    printf "* Not setting colors for terminator (target file not found: ${TERMINATOR_CONFIG_FILE}).\n"
-    
+    printf "* Not setting colors for terminator (configuration file not found: ${TERMINATOR_CONFIG_FILE}).\n"
+
 else
     printf "* Setting colors for terminator..."
     terminator_set_value_default_profile "background_color" "${terminal_bg_color}"  "${TERMINATOR_CONFIG_FILE}"
