Improved Code::Blocks module

diff --git a/src/share/modules/codeblocks b/src/share/modules/codeblocks
--- a/src/share/modules/codeblocks
+++ b/src/share/modules/codeblocks
@@ -27,9 +27,9 @@ codeblocks_add_style() {
     xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/NAME" --type elem -n "str" --value "${name}" "${file}"
     
     if [ "${fg_color}" != "default" ]; then
-        local fg_red="$(printf   "%d" 0x${fg_color:1:2})"
-        local fg_green="$(printf "%d" 0x${fg_color:3:2})"
-        local fg_blue="$(printf  "%d" 0x${fg_color:5:2})"
+        local fg_red="$(   printf "%d" 0x${fg_color:1:2})"
+        local fg_green="$( printf "%d" 0x${fg_color:3:2})"
+        local fg_blue="$(  printf "%d" 0x${fg_color:5:2})"
         
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"             --type elem -n "FORE"                         "${file}"
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE"        --type elem -n "colour"                       "${file}"
@@ -39,9 +39,9 @@ codeblocks_add_style() {
     fi
     
     if [ "${bg_color}" != "default" ]; then
-        local bg_red="$(printf   "%d" 0x${bg_color:1:2})"
-        local bg_green="$(printf "%d" 0x${bg_color:3:2})"
-        local bg_blue="$(printf  "%d" 0x${bg_color:5:2})"
+        local bg_red="$(   printf "%d" 0x${bg_color:1:2})"
+        local bg_green="$( printf "%d" 0x${bg_color:3:2})"
+        local bg_blue="$(  printf "%d" 0x${bg_color:5:2})"
         
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"             --type elem -n "BACK"                         "${file}"
         xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"        --type elem -n "colour"                       "${file}"
@@ -53,7 +53,26 @@ codeblocks_add_style() {
     CB_STYLE_CTR="$(expr $CB_STYLE_CTR + 1)"
 }
 
-
+codeblocks_set_color (){
+    
+    if [ "$#" -ne 3 ]; then
+	    echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
+	    exit 2
+    fi
+    
+    local path="$1"
+    local color="$2"
+    local file="$3"
+    
+    local red="$(   printf "%d" 0x${color:1:2})"
+    local green="$( printf "%d" 0x${color:3:2})"
+    local blue="$(  printf "%d" 0x${color:5:2})"
+    
+    xmlstarlet ed --inplace --update "${path}/colour/@r" --value "${red}"   "${file}"
+    xmlstarlet ed --inplace --update "${path}/colour/@g" --value "${green}" "${file}"
+    xmlstarlet ed --inplace --update "${path}/colour/@b" --value "${blue}"  "${file}"
+    
+}
 
 CODEBLOCKS_CONFIG_FILE="$HOME/.codeblocks/default.conf"
 
@@ -76,22 +95,35 @@ if [ -f "${CODEBLOCKS_CONFIG_FILE}" ]; then
     codeblocks_add_style "Default"   "cc" "${editor_fg}"          "${editor_bg}"          "${CODEBLOCKS_CONFIG_FILE}"
     codeblocks_add_style "Selection" "cc" "${editor_selected_fg}" "${editor_selected_bg}" "${CODEBLOCKS_CONFIG_FILE}"
     
-    codeblocks_add_style "Number"                                "cc" "${editor_number}"       "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "User keyword"                          "cc" "${editor_class}"        "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "String"                                "cc" "${editor_string}"       "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Operator"                              "cc" "${editor_operator}"     "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Comment (normal)"                      "cc" "${editor_comment}"      "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Comment line (normal)"                 "cc" "${editor_comment}"      "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Comment (documentation)"               "cc" "${editor_comment}"      "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Comment line (documentation)"          "cc" "${editor_comment}"      "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Comment keyword (documentation)"       "cc" "${editor_preprocessor}" "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Comment keyword error (documentation)" "cc" "${editor_error}"        "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Keyword"                               "cc" "${editor_keyword}"      "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Character"                             "cc" "${editor_character}"    "default" "${CODEBLOCKS_CONFIG_FILE}"
-    codeblocks_add_style "Preprocessor"                          "cc" "${editor_preprocessor}" "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Number"                                "cc" "${editor_number}"          "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "User keyword"                          "cc" "${editor_class}"           "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "String"                                "cc" "${editor_string}"          "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Operator"                              "cc" "${editor_operator}"        "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Comment (normal)"                      "cc" "${editor_comment}"         "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Comment line (normal)"                 "cc" "${editor_comment}"         "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Comment (documentation)"               "cc" "${editor_comment}"         "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Comment line (documentation)"          "cc" "${editor_comment}"         "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Comment keyword (documentation)"       "cc" "${editor_preprocessor}"    "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Comment keyword error (documentation)" "cc" "${editor_error}"           "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Keyword"                               "cc" "${editor_keyword}"         "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Character"                             "cc" "${editor_character}"       "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Preprocessor"                          "cc" "${editor_preprocessor}"    "default" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_add_style "Active line"                           "cc" "${editor_current_line_bg}" "default" "${CODEBLOCKS_CONFIG_FILE}"
     
     # set new colorset as active
     xmlstarlet ed --inplace --update "${CB_PREFIX}/ACTIVE_COLOUR_SET/str" --value "${CB_COLORSET_NAME}" "${CODEBLOCKS_CONFIG_FILE}"
+    
+    codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/ACTIVE_CAPTION_COLOUR"            "${selected_bg_color}"    "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/ACTIVE_CAPTION_GRADIENT_COLOUR"   "${selected_bg_color}"    "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/ACTIVE_CAPTION_TEXT_COLOUR"       "${selected_fg_color}"    "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/INACTIVE_CAPTION_COLOUR"          "${unfocused_color}"      "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/INACTIVE_CAPTION_GRADIENT_COLOUR" "${unfocused_color}"      "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "/CodeBlocksConfig/app/environment/aui/INACTIVE_CAPTION_TEXT_COLOUR"     "${unfocused_text_color}" "${CODEBLOCKS_CONFIG_FILE}"
+    
+    codeblocks_set_color "CodeBlocksConfig/colours/list/EDITOR_MARGIN_CHROME"           "${bg_color}" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "CodeBlocksConfig/colours/list/EDITOR_MARGIN_CHROME_HIGHLIGHT" "${bg_color}" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "CodeBlocksConfig/colours/list/EDITOR_LINENUMBERS_BG"          "${bg_color}" "${CODEBLOCKS_CONFIG_FILE}"
+    codeblocks_set_color "CodeBlocksConfig/colours/list/EDITOR_LINENUMBERS_FG"          "${fg_color}" "${CODEBLOCKS_CONFIG_FILE}"
     
     echo "  Done."
 fi
