Imrovements to dunst module

diff --git a/src/share/modules/dunst b/src/share/modules/dunst
--- a/src/share/modules/dunst
+++ b/src/share/modules/dunst
@@ -1,17 +1,29 @@
 #!/bin/sh
 
-DUNST_CONFIG_FILE="$HOME/.config/dunst/dunstrc"
 DUNST_RESTART_COMMAND=$(crudini --get ${CONFIG_FILE} dunst restart_command 2>/dev/null || echo )
+
+DUNST_CONFIG_FILE_DEFAULT="$HOME/.config/dunst/dunstrc"
+DUNST_CONFIG_FILE="$(crudini --get ${CONFIG_FILE} dunst config_file 2>/dev/null || echo "${DUNST_CONFIG_FILE_DEFAULT}")"
+
+: ${dunst_frame:=${notification_frame}}
+: ${dunst_urgency_low_bg:=${notification_low_bg}}
+: ${dunst_urgency_low_fg:=${notification_low_fg}}
+: ${dunst_urgency_normal_bg:=${notification_medium_bg}}
+: ${dunst_urgency_normal_fg:=${notification_medium_fg}}
+: ${dunst_urgency_critical_bg:=${notification_high_bg}}
+: ${dunst_urgency_critical_fg:=${notification_high_fg}}
 
 if [ -f "${DUNST_CONFIG_FILE}" ]; then
     printf "* Setting colors for dunst..."
-    set_value_section "frame"            "color"      " = " "\"$notification_frame\""     "$DUNST_CONFIG_FILE"
-    set_value_section "urgency_low"      "background" " = " "\"$notification_low_bg\""    "$DUNST_CONFIG_FILE"
-    set_value_section "urgency_low"      "foreground" " = " "\"$notification_low_fg\""    "$DUNST_CONFIG_FILE"
-    set_value_section "urgency_normal"   "background" " = " "\"$notification_medium_bg\"" "$DUNST_CONFIG_FILE"
-    set_value_section "urgency_normal"   "foreground" " = " "\"$notification_medium_fg\"" "$DUNST_CONFIG_FILE"
-    set_value_section "urgency_critical" "background" " = " "\"$notification_high_bg\""   "$DUNST_CONFIG_FILE"
-    set_value_section "urgency_critical" "foreground" " = " "\"$notification_high_fg\""   "$DUNST_CONFIG_FILE"
+    set_value_section "frame"            "color"      " = " "\"${dunst_frame}\""               "${DUNST_CONFIG_FILE}"
+    set_value_section "urgency_low"      "background" " = " "\"${dunst_urgency_low_bg}\""      "${DUNST_CONFIG_FILE}"
+    set_value_section "urgency_low"      "foreground" " = " "\"${dunst_urgency_low_fg}\""      "${DUNST_CONFIG_FILE}"
+    set_value_section "urgency_normal"   "background" " = " "\"${dunst_urgency_normal_bg}\""   "${DUNST_CONFIG_FILE}"
+    set_value_section "urgency_normal"   "foreground" " = " "\"${dunst_urgency_normal_fg}\""   "${DUNST_CONFIG_FILE}"
+    set_value_section "urgency_critical" "background" " = " "\"${dunst_urgency_critical_bg}\"" "${DUNST_CONFIG_FILE}"
+    set_value_section "urgency_critical" "foreground" " = " "\"${dunst_urgency_critical_fg}\"" "${DUNST_CONFIG_FILE}"
     $DUNST_RESTART_COMMAND &>/dev/null
     printf " done.\n"
+else
+    printf "* Not setting colors for dunst (config file \"${DUNST_CONFIG_FILE}\" not found).\n"
 fi
