Added checks for i3 window manager

diff --git a/src/share/modules/i3wm b/src/share/modules/i3wm
--- a/src/share/modules/i3wm
+++ b/src/share/modules/i3wm
@@ -2,7 +2,11 @@
 # FIXME: sed gives errors if the relevant lines have also commented copies
 
 I3_CONFIG_FILE="$HOME/.config/i3/config"
-if [ -f "${I3_CONFIG_FILE}" ]; then
+if ! [ -f "${I3_CONFIG_FILE}" ]; then
+    printf "* Not setting colors for i3 window manager (configuration file \"${I3_CONFIG_FILE}\" not found).\n"
+elif ! [/tmp/i3-ipc.sock]; then
+    printf "* Not setting colors for i3 window manager (not currently active).\n"
+else
     printf "* Setting colors for i3 window manager..."
     
     set_value "client\.focused"          " " "${titlebar_focused_bg_color}   ${titlebar_focused_bg_color}   ${titlebar_focused_fg_color}   ${titlebar_focused_bg_color}"   "${I3_CONFIG_FILE}"
