Add -n option to perform a dry-run

diff --git a/src/gcs b/src/gcs
--- a/src/gcs
+++ b/src/gcs
@@ -45,6 +45,7 @@ function print_help() {
     echo
     echo "Available options:"
     echo "  -m <module>    execute only one module"
+    echo "  -n             do not apply theme, just print what would happen"
     echo "  -h             show this help screen"
     echo "  -u             update base16 schemes"
     echo
@@ -81,7 +82,7 @@ function update_base16_schemes() {
 }
 
 function parse_options() {
-    while getopts ":m:b:r:hu" opt; do
+    while getopts ":m:b:r:nhu" opt; do
         case $opt in
           m)
             FORCED_MODULE="$OPTARG"
@@ -95,6 +96,10 @@ function parse_options() {
           r)
             GCS_ACTION="restore-backup"
             GCS_BACKUP_NAME="$OPTARG"
+            shift $((OPTIND-1))
+            ;;
+          n)
+            GCS_ACTION="dry-run"
             shift $((OPTIND-1))
             ;;
           h)
@@ -116,12 +121,16 @@ function parse_options() {
         OPTIND=1
     done
 
-    if [ "${GCS_ACTION}" == "apply-theme" ]; then
+    if [[ "${GCS_ACTION}" == "apply-theme" || "${GCS_ACTION}" == "dry-run" ]]; then
         COLOR_THEME_NAME="$1"
         shift
     fi
 
     if [[ "${GCS_ACTION}" == "apply-theme" && "${COLOR_THEME_NAME}" == "" ]]; then
+        print_help
+    fi
+
+    if [[ "${GCS_ACTION}" == "dry-run" && "${COLOR_THEME_NAME}" == "" ]]; then
         print_help
     fi
 
@@ -461,6 +470,18 @@ function select_action() {
 
         echo "Applying color theme ${COLOR_THEME_NAME}"
 
+    elif [ "${GCS_ACTION}" == "dry-run" ]; then
+        if [ -f "${GCS_THEMES_DIR_USER}/${COLOR_THEME_NAME}/colortheme" ]; then true
+        elif  [ -f "${GCS_THEMES_DIR_LOCAL}/${COLOR_THEME_NAME}/colortheme" ]; then true
+        elif  [ -f "${GCS_THEMES_DIR_SYSTEM}/${COLOR_THEME_NAME}/colortheme" ]; then true
+        else
+            echo "Error: theme \"${COLOR_THEME_NAME}\" not found!"
+            exit 2
+        fi
+
+        echo "Dry run, no actual action will be performed."
+        echo "Instead, each module will briefly describe what it would do."
+
     elif [ "${GCS_ACTION}" == "create-backup" ]; then
         if [ -d "${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}" ]; then
             echo "Error: backup \"${GCS_BACKUP_NAME}\" already exists!"
@@ -516,6 +537,7 @@ function execute_modules() {
         function derive_colors()      { true; }
         function create_backup()      { true; }
         function restore_backup()     { true; }
+        function dry_run()            { true; }
         function apply_theme()        { true; }
 
         # Load module
@@ -529,6 +551,7 @@ function execute_modules() {
         case "${GCS_ACTION}" in
             "create-backup")  create_backup;;
             "restore-backup") restore_backup;;
+            "dry-run")        dry_run;;
             "apply-theme")    derive_colors; apply_theme;;
         esac
     done
