Implement backup/restore for most modules, and stubs for the others

diff --git a/src/gcs b/src/gcs
--- a/src/gcs
+++ b/src/gcs
@@ -24,19 +24,35 @@ GCS_MODULES_DIR_USER="$HOME/.local/share/gcs/modules"
 GCS_THEMES_DIR_SYSTEM="/usr/share/gcs/colorthemes"
 GCS_THEMES_DIR_LOCAL="/usr/local/share/gcs/colorthemes"
 GCS_THEMES_DIR_USER="$HOME/.config/gcs/colorthemes"
+GCS_BACKUPS_DIR="$HOME/.local/share/gcs/backups"
 
 GCS_CONFIG_DIR="$HOME/.config/gcs"
 GCS_CONFIG_FILE="${GCS_CONFIG_DIR}/gcs.conf"
 GCS_TMP_DIR="$(mktemp -d -t .gcs-XXXXXX)"
 GCS_LOCK_FILE="/tmp/.gcs_lock"
 
-while getopts "m:" opt; do
+GCS_ACTION="apply-theme"
+GCS_BACKUP_NAME=""
+
+while getopts "m:b:r:" opt; do
   case $opt in
     m)
       FORCED_MODULE="$OPTARG"
       shift
       shift
       ;;
+    b)
+      GCS_ACTION="create-backup"
+      GCS_BACKUP_NAME="$OPTARG"
+      shift
+      shift
+    ;;
+    r)
+      GCS_ACTION="restore-backup"
+      GCS_BACKUP_NAME="$OPTARG"
+      shift
+      shift
+    ;;
     \?)
       echo "Invalid option: -$OPTARG" >&2
       exit 1
@@ -48,18 +64,27 @@ while getopts "m:" opt; do
   esac
 done
 
-if [ "$#" -ne 1 ]; then
-    echo "Usage: $0 [options] <color_theme_name>"
+if [ "${GCS_ACTION}" == "apply-theme" ]; then
+    COLOR_THEME_NAME="$1"
+    shift
+fi
+
+
+if [ "$#" -ne 0 ]; then
+    echo "Usage: $0 [options] [ <color_theme_name> ]"
+    echo
+    echo "<color_theme_name> should be given for normal use, but not when making/restoring a backup"
     echo
     echo "Available options:"
     echo -e "\t-m <module>\texecute only one module"
+    echo -b "\t-m <backup_name>\tmake a backup"
+    echo -e "\t-m <backup_name>\trestore a backup"
     echo
     echo "Avilable color themes:"
     find "${HOME}/.config/gcs/colorthemes" "/usr/local/share/gcs/colorthemes" "/usr/share/gcs/colorthemes" \
         -mindepth 1 -maxdepth 1 -type d -printf "\t%f\n" 2>/dev/null | sort | uniq
     exit 1
 fi
-COLOR_THEME_NAME="$1"
 
 # Load a color theme file.
 # egrep is used to only select lines which contain declaration for variables containing only
@@ -266,21 +291,40 @@ cleanup() {
     rm -r "${GCS_TMP_DIR}" &>/dev/null
 }
 
-
-if [ -f "${GCS_THEMES_DIR_USER}/${COLOR_THEME_NAME}/colortheme" ]; then true
-elif  [ -f "${GCS_THEMES_DIR_LOCAL}/${COLOR_THEME_NAME}/colortheme" ]; then true
-elif  [ -f "${GCS_THEMES_DIR_SYSTEM}/${COLOR_THEME_NAME}/colortheme" ]; then true
-else
-    echo "Error: theme \"${COLOR_THEME_NAME}\" not found!"
-    exit 2
-fi
-
 if [ -f "${GCS_LOCK_FILE}" ]; then
     echo "Error: lockfile \"${GCS_LOCK_FILE}\" exists, exiting."
     exit 3
 fi
 
-echo "Applying color theme ${COLOR_THEME_NAME}"
+if [ "${GCS_ACTION}" == "apply-theme" ]; then
+    if [ -f "${GCS_THEMES_DIR_USER}/${COLOR_THEME_NAME}/colortheme" ]; then true
+    elif  [ -f "${GCS_THEMES_DIR_LOCAL}/${COLOR_THEME_NAME}/colortheme" ]; then true
+    elif  [ -f "${GCS_THEMES_DIR_SYSTEM}/${COLOR_THEME_NAME}/colortheme" ]; then true
+    else
+        echo "Error: theme \"${COLOR_THEME_NAME}\" not found!"
+        exit 2
+    fi
+
+    echo "Applying color theme ${COLOR_THEME_NAME}"
+
+elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    if [ -d "${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}" ]; then
+        echo "Error: backup \"${GCS_BACKUP_NAME}\" already exists!"
+        exit 3
+    fi
+
+    echo "Creating backup in \"${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}\""
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    if ! [ -d "${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}" ]; then
+        echo "Error: backup \"${GCS_BACKUP_NAME}\" does not exist!"
+        exit 4
+    fi
+
+    echo "Restoring backup from \"${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}\""
+
+fi
+
 touch "${GCS_LOCK_FILE}"
 trap "cleanup; exit 1" INT
 
diff --git a/src/share/modules/background-nautilus b/src/share/modules/background-nautilus
--- a/src/share/modules/background-nautilus
+++ b/src/share/modules/background-nautilus
@@ -15,30 +15,43 @@ for i in ${COLOR_THEME_DIRS[@]}; do
 done
 
 if ! [ "${BACKGROUND_NAUTILUS_ENABLE}" == "true" ]; then
-    printf "* Not setting wallpaper with nautilus (disabled from configuration).\n"
-    
-elif ! [ -f "${wallpaper_file}" ]; then
-    printf "* Not setting wallpaper with nautilus (image file not found: \"${wallpaper_image}\").\n"
-    
-elif ! pgrep "nautilus" >/dev/null; then
-    printf "* Not setting wallpaper with nautilus (desktop manager is not active).\n"
-    
-else
-    printf "* Setting wallpaper with nautilus..."
-    gsettings set org.gnome.desktop.background picture-uri "file://${COLOR_THEME_DIR}/${wallpaper_image}"
-    gsettings set org.gnome.desktop.background color-shading-type "solid"
-    gsettings set org.gnome.desktop.background primary-color "${wallpaper_bg_color}"
-    case "${wallpaper_mode}" in
-        centered)  gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
-                   gsettings set org.gnome.desktop.background picture-options "centered";;
-        tiled)     gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
-                   gsettings set org.gnome.desktop.background picture-options "spanned";;
-        stretched) gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
-                   gsettings set org.gnome.desktop.background picture-options "stretched";;
-        zoom-fit)  gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
-                   gsettings set org.gnome.desktop.background picture-options "scaled";;
-        zoom-fill) gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
-                   gsettings set org.gnome.desktop.background picture-options "zoom";;
-    esac
-    printf " done.\n"
+    printf "* Ignoring wallpaper for nautilus (disabled from configuration).\n"
+
+elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    printf "* Backup/restore not supported with nautilus wallpaper.\n"
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    printf "* Backup/restore not supported with nautilus wallpaper.\n"
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    if ! [ -f "${wallpaper_file}" ]; then
+        printf "* Not setting wallpaper with nautilus (image file not found: \"${wallpaper_image}\").\n"
+
+    elif ! pgrep "nautilus" >/dev/null; then
+        printf "* Not setting wallpaper with nautilus (desktop manager is not active).\n"
+
+    else
+        printf "* Setting wallpaper with nautilus..."
+
+        gsettings set org.gnome.desktop.background picture-uri "file://${COLOR_THEME_DIR}/${wallpaper_image}"
+        gsettings set org.gnome.desktop.background color-shading-type "solid"
+        gsettings set org.gnome.desktop.background primary-color "${wallpaper_bg_color}"
+
+        case "${wallpaper_mode}" in
+            centered)  gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
+                       gsettings set org.gnome.desktop.background picture-options "centered";;
+            tiled)     gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
+                       gsettings set org.gnome.desktop.background picture-options "spanned";;
+            stretched) gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
+                       gsettings set org.gnome.desktop.background picture-options "stretched";;
+            zoom-fit)  gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
+                       gsettings set org.gnome.desktop.background picture-options "scaled";;
+            zoom-fill) gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper_file}"
+                       gsettings set org.gnome.desktop.background picture-options "zoom";;
+        esac
+        printf " done.\n"
+
+    fi
+
 fi
+
diff --git a/src/share/modules/background-nitrogen b/src/share/modules/background-nitrogen
--- a/src/share/modules/background-nitrogen
+++ b/src/share/modules/background-nitrogen
@@ -14,19 +14,30 @@ for i in ${COLOR_THEME_DIRS[@]}; do
 done
 
 if ! [ "${NITROGEN_ENABLE}" == "true" ]; then
-    printf "* Not setting wallpaper with nitrogen (disabled from configuration).\n"
-    
-elif ! [ -f "${wallpaper_file}" ]; then
-    printf "* Not setting wallpaper with nitrogen (image file not found: \"${wallpaper_image}\").\n"
-    
-else
-    printf "* Setting wallpaper with nitrogen..."
-    case "${wallpaper_mode}" in
-        centered)  nitrogen --save --set-centered "${wallpaper_file}" --set-color=${wallpaper_bg_color};;
-        tiled)     nitrogen --save --set-tiled "${wallpaper_file}";;
-        stretched) nitrogen --save --set-scaled "${wallpaper_file}";;
-        zoom-fit)  nitrogen --save --set-zoom "${wallpaper_file}" --set-color=${wallpaper_bg_color};;
-        zoom-fill) nitrogen --save --set-zoom-fill "${wallpaper_file}";;
-    esac
-    printf " done.\n"
+    printf "* Ignoring wallpaper for nitrogen (disabled from configuration).\n"
+
+elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    printf "* Backup/restore not supported with nitrogen.\n"
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    printf "* Backup/restore not supported with nitrogen.\n"
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    if ! [ -f "${wallpaper_file}" ]; then
+        printf "* Not setting wallpaper with nitrogen (image file not found: \"${wallpaper_image}\").\n"
+
+    else
+        printf "* Setting wallpaper with nitrogen..."
+        case "${wallpaper_mode}" in
+            centered)  nitrogen --save --set-centered "${wallpaper_file}" --set-color=${wallpaper_bg_color};;
+            tiled)     nitrogen --save --set-tiled "${wallpaper_file}";;
+            stretched) nitrogen --save --set-scaled "${wallpaper_file}";;
+            zoom-fit)  nitrogen --save --set-zoom "${wallpaper_file}" --set-color=${wallpaper_bg_color};;
+            zoom-fill) nitrogen --save --set-zoom-fill "${wallpaper_file}";;
+        esac
+        printf " done.\n"
+
+    fi
+
 fi
+
diff --git a/src/share/modules/background-pcmanfm b/src/share/modules/background-pcmanfm
--- a/src/share/modules/background-pcmanfm
+++ b/src/share/modules/background-pcmanfm
@@ -14,29 +14,40 @@ for i in ${COLOR_THEME_DIRS[@]}; do
 done
 
 if ! [ "${BACKGROUND_PCMANFM_ENABLE}" == "true" ]; then
-    printf "* Not setting wallpaper with pcmanfm (disabled from configuration).\n"
-    
-elif ! [ -f "${wallpaper_file}" ]; then
-    printf "* Not setting wallpaper with pcmanfm (image file not found: \"${wallpaper_image}\").\n"
-    
-elif ! pgrep -f "pcmanfm --desktop" >/dev/null; then
-    printf "* Not setting wallpaper with pcmanfm (desktop manager is not active).\n"
-    
-else
-    printf "* Setting wallpaper with pcmanfm..."
-    
-    case "${wallpaper_mode}" in
-        centered)  pcmanfm --wallpaper-mode=center  --set-wallpaper "${wallpaper_file}";;
-        tiled)     pcmanfm --wallpaper-mode=tile    --set-wallpaper "${wallpaper_file}";;
-        stretched) pcmanfm --wallpaper-mode=stretch --set-wallpaper "${wallpaper_file}";;
-        zoom-fit)  pcmanfm --wallpaper-mode=fit     --set-wallpaper "${wallpaper_file}";;
-        zoom-fill) pcmanfm --wallpaper-mode=crop    --set-wallpaper "${wallpaper_file}";;
-    esac
+    printf "* Ignoring wallpaper for pcmanfm (disabled from configuration).\n"
 
-    # these require a patched version of PCManFM: https://github.com/livanh/pcmanfm (master-with improvements branch)
-    pcmanfm --wallpaper-bg-color ${wallpaper_bg_color}
-    pcmanfm --desktop-text-color ${wallpaper_text_color}
-    pcmanfm --desktop-shadow-color ${wallpaper_shadow_color}
+elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    printf "* Backup/restore not supported with pcmanfm wallpaper.\n"
 
-    printf " done.\n"
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    printf "* Backup/restore not supported with pcmanfm wallpaper.\n"
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    if ! [ -f "${wallpaper_file}" ]; then
+        printf "* Not setting wallpaper with pcmanfm (image file not found: \"${wallpaper_image}\").\n"
+
+    elif ! pgrep -f "pcmanfm --desktop" >/dev/null; then
+        printf "* Not setting wallpaper with pcmanfm (desktop manager is not active).\n"
+
+    else
+        printf "* Setting wallpaper with pcmanfm..."
+
+        case "${wallpaper_mode}" in
+            centered)  pcmanfm --wallpaper-mode=center  --set-wallpaper "${wallpaper_file}";;
+            tiled)     pcmanfm --wallpaper-mode=tile    --set-wallpaper "${wallpaper_file}";;
+            stretched) pcmanfm --wallpaper-mode=stretch --set-wallpaper "${wallpaper_file}";;
+            zoom-fit)  pcmanfm --wallpaper-mode=fit     --set-wallpaper "${wallpaper_file}";;
+            zoom-fill) pcmanfm --wallpaper-mode=crop    --set-wallpaper "${wallpaper_file}";;
+        esac
+
+        # these require a patched version of PCManFM: https://github.com/livanh/pcmanfm (master-with improvements branch)
+        pcmanfm --wallpaper-bg-color ${wallpaper_bg_color}
+        pcmanfm --desktop-text-color ${wallpaper_text_color}
+        pcmanfm --desktop-shadow-color ${wallpaper_shadow_color}
+
+        printf " done.\n"
+
+    fi
+
 fi
+
diff --git a/src/share/modules/xresources b/src/share/modules/xresources
--- a/src/share/modules/xresources
+++ b/src/share/modules/xresources
@@ -32,15 +32,32 @@ XRESOURCES_ADDITIONAL_COMMANDS="$(crudini --get ${GCS_CONFIG_FILE} xresources ad
 : ${xresources_tray_urgent_fg_color:=${tray_urgent_fg_color}}
 
 if ! [ "${XRESOURCES_ENABLE}" == "true" ]; then
-    printf "* Not setting Xresources colors (disabled from configuration).\n"
+    printf "* Ignoring Xresources colors (disabled from configuration).\n"
 
-else
+elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    printf "* Making backup of Xresources file..."
+
+    XRESOURCES_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/xresources"
+    mkdir -p "${XRESOURCES_BACKUP_DIR}"
+    cp "${XRESOURCES_CONFIG_FILE}" "${XRESOURCES_BACKUP_DIR}/Xresources"
+
+    printf " done.\n"
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    printf "* Restoring backup of Xresources file..."
+
+    XRESOURCES_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/xresources"
+    [ -f "${XRESOURCES_BACKUP_DIR}/Xresources" ] && cp "${XRESOURCES_BACKUP_DIR}/Xresources" "${XRESOURCES_CONFIG_FILE}" || echo "not found"
+
+    printf " done.\n"
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
     [ -f "${XRESOURCES_CONFIG_FILE}" ] || touch "${XRESOURCES_CONFIG_FILE}"
 
     printf "* Setting Xresources colors..."
 
     XRESOURCES_TMP_DIR="${GCS_TMP_DIR}/xresources"
-    XRESOURCES_TMP_CONFIG_FILE="${XRESOURCES_TMP_DIR}/xresources"
+    XRESOURCES_TMP_CONFIG_FILE="${XRESOURCES_TMP_DIR}/Xresources"
     mkdir "${XRESOURCES_TMP_DIR}"
     cp "${XRESOURCES_CONFIG_FILE}" "${XRESOURCES_TMP_CONFIG_FILE}"
 
@@ -71,4 +88,6 @@ else
     $XRESOURCES_ADDITIONAL_COMMANDS &>/dev/null
 
     printf " done.\n"
+
 fi
+
