Wrap all code into functions

diff --git a/src/gcs b/src/gcs
--- a/src/gcs
+++ b/src/gcs
@@ -17,27 +17,27 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+function initialize_environment() {
+    GCS_MODULES_DIR_SYSTEM="/usr/share/gcs/modules"
+    GCS_MODULES_DIR_LOCAL="/usr/local/share/gcs/modules"
+    GCS_MODULES_DIR_USER="$HOME/.local/share/gcs/modules"
+    GCS_THEMES_DIR_SYSTEM="/usr/share/gcs/colorthemes"
+    GCS_THEMES_DIR_LOCAL="/usr/local/share/gcs/colorthemes"
+    GCS_THEMES_DIR_USER="$HOME/.config/gcs/colorthemes"
+    GCS_BASE16_SCHEMES_REPOSITORY="https://github.com/chriskempson/base16-schemes-source"
+    GCS_BASE16_SCHEMES_DIR_USER="$HOME/.config/gcs/base16"
+    GCS_BACKUPS_DIR="$HOME/.local/share/gcs/backups"
 
-GCS_MODULES_DIR_SYSTEM="/usr/share/gcs/modules"
-GCS_MODULES_DIR_LOCAL="/usr/local/share/gcs/modules"
-GCS_MODULES_DIR_USER="$HOME/.local/share/gcs/modules"
-GCS_THEMES_DIR_SYSTEM="/usr/share/gcs/colorthemes"
-GCS_THEMES_DIR_LOCAL="/usr/local/share/gcs/colorthemes"
-GCS_THEMES_DIR_USER="$HOME/.config/gcs/colorthemes"
-GCS_BASE16_SCHEMES_REPOSITORY="https://github.com/chriskempson/base16-schemes-source"
-GCS_BASE16_SCHEMES_DIR_USER="$HOME/.config/gcs/base16"
-GCS_BACKUPS_DIR="$HOME/.local/share/gcs/backups"
+    GCS_CONFIG_DIR="$HOME/.config/gcs"
+    GCS_CONFIG_FILE="${GCS_CONFIG_DIR}/gcs.conf"
+    GCS_TMP_DIR="$(mktemp -d -t .gcs-XXXXXX)"
+    GCS_LOCK_FILE="/tmp/.gcs_lock"
 
-GCS_CONFIG_DIR="$HOME/.config/gcs"
-GCS_CONFIG_FILE="${GCS_CONFIG_DIR}/gcs.conf"
-GCS_TMP_DIR="$(mktemp -d -t .gcs-XXXXXX)"
-GCS_LOCK_FILE="/tmp/.gcs_lock"
+    GCS_ACTION="apply-theme"
+    GCS_BACKUP_NAME=""
+}
 
-GCS_ACTION="apply-theme"
-GCS_BACKUP_NAME=""
-
-
-help() {
+function print_help() {
     echo "Usage:"
     echo "  to apply a color theme:   $0 [options] <color_theme_name>"
     echo "  to create a backup:       $0 [options] -b <backup_name>"
@@ -58,7 +58,7 @@ help() {
     exit 1
 }
 
-update_base16_schemes() {
+function update_base16_schemes() {
     local GCS_BASE16_LIST="${GCS_TMP_DIR}/base16-list"
     local GCS_BASE16_TEMP="${GCS_TMP_DIR}/base16-temp"
     [ -d "${GCS_BASE16_SCHEMES_DIR_USER}" ] || mkdir -p "${GCS_BASE16_SCHEMES_DIR_USER}"
@@ -80,56 +80,58 @@ update_base16_schemes() {
     echo "Done."
 }
 
-while getopts ":m:b:r:hu" opt; do
-    case $opt in
-      m)
-        FORCED_MODULE="$OPTARG"
-        shift $((OPTIND-1))
-        ;;
-      b)
-        GCS_ACTION="create-backup"
-        GCS_BACKUP_NAME="$OPTARG"
-        shift $((OPTIND-1))
-        ;;
-      r)
-        GCS_ACTION="restore-backup"
-        GCS_BACKUP_NAME="$OPTARG"
-        shift $((OPTIND-1))
-        ;;
-      h)
-        help
-        ;;
-      u)
-        update_base16_schemes
-        exit 1
-        ;;
-      \?)
-        echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-      :)
-        echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
-    esac
-    OPTIND=1
-done
+function parse_options() {
+    while getopts ":m:b:r:hu" opt; do
+        case $opt in
+          m)
+            FORCED_MODULE="$OPTARG"
+            shift $((OPTIND-1))
+            ;;
+          b)
+            GCS_ACTION="create-backup"
+            GCS_BACKUP_NAME="$OPTARG"
+            shift $((OPTIND-1))
+            ;;
+          r)
+            GCS_ACTION="restore-backup"
+            GCS_BACKUP_NAME="$OPTARG"
+            shift $((OPTIND-1))
+            ;;
+          h)
+            print_help
+            ;;
+          u)
+            update_base16_schemes
+            exit 1
+            ;;
+          \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+          :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+        esac
+        OPTIND=1
+    done
 
-if [ "${GCS_ACTION}" == "apply-theme" ]; then
-    COLOR_THEME_NAME="$1"
-    shift
-fi
+    if [ "${GCS_ACTION}" == "apply-theme" ]; then
+        COLOR_THEME_NAME="$1"
+        shift
+    fi
+
+    if [[ "${GCS_ACTION}" == "apply-theme" && "${COLOR_THEME_NAME}" == "" ]]; then
+        print_help
+    fi
+
+    if [ "$#" -ne 0 ]; then
+        print_help
+    fi
+}
 
 
-if [[ "${GCS_ACTION}" == "apply-theme" && "${COLOR_THEME_NAME}" == "" ]]; then
-    help
-fi
-
-if [ "$#" -ne 0 ]; then
-    help
-fi
-
-load_base16_scheme() {
+function load_base16_scheme() {
     if [ "$#" -ne 1 ]; then
         echo "Error: load_base16_scheme() requires 1 argument!"
         exit 2
@@ -162,7 +164,7 @@ load_base16_scheme() {
     base0F="$(awk '/base0F:/{print "#"substr($2,2,6)}' "${base16_scheme_file}")"
 }
 
-compare_brightness() {
+function compare_brightness() {
     if [ "$#" -ne 1 ]; then
         echo "Error: compare_brightness() requires 2 arguments!"
         exit 2
@@ -189,7 +191,7 @@ compare_brightness() {
 # alphanumeric characters, hashtags (for hexadecimal colours, i.e. #FF0000), dollar signs and underscores
 # (to reuse other variables, i.e. var=$var_2), dots (for filenames) and hyphens (for icon theme names).
 # Single or double quotes are permitted.
-load_color_theme() {
+function load_color_theme() {
 
     if [ "$#" -ne 1 ]; then
         echo "Error: load_color_theme() requires 1 argument!"
@@ -396,7 +398,7 @@ load_color_theme() {
 # assuming they are separated by $SEPARATOR
 # warning: do not use for config file with different sections, because
 # if the key does not exist, it will be created at the end of the file
-set_value() {
+function set_value() {
     if [ "$#" -ne 4 ]; then
         echo "Error: set_value() requires 4 arguments!"
         exit 2
@@ -415,7 +417,7 @@ set_value() {
 # set the value of the key named $KEY (in section [section] on text
 # file $FILE) equal to $VALUE, assuming they are separated by $SEPARATOR
 # TODO: define behaviour when $SECTION is not found
-set_value_section() {
+function set_value_section() {
     if [ "$#" -ne 5 ]; then
         echo "Error: set_value_section() requires 5 arguments!"
         exit 2
@@ -433,75 +435,92 @@ set_value_section() {
     rm $tmp_file
 }
 
-cleanup() {
+function cleanup() {
     rm "${GCS_LOCK_FILE}"
     rm -r "${GCS_TMP_DIR}" &>/dev/null
 }
 
-if [ -f "${GCS_LOCK_FILE}" ]; then
-    echo "Error: lockfile \"${GCS_LOCK_FILE}\" exists, exiting."
-    exit 3
-fi
-
-if [ "${GCS_ACTION}" == "apply-theme" ]; then
-    if [ -f "${GCS_THEMES_DIR_USER}/${COLOR_THEME_NAME}/colortheme" ]; then true
-    elif  [ -f "${GCS_THEMES_DIR_LOCAL}/${COLOR_THEME_NAME}/colortheme" ]; then true
-    elif  [ -f "${GCS_THEMES_DIR_SYSTEM}/${COLOR_THEME_NAME}/colortheme" ]; then true
-    else
-        echo "Error: theme \"${COLOR_THEME_NAME}\" not found!"
-        exit 2
-    fi
-
-    echo "Applying color theme ${COLOR_THEME_NAME}"
-
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
-    if [ -d "${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}" ]; then
-        echo "Error: backup \"${GCS_BACKUP_NAME}\" already exists!"
+function lock() {
+    if [ -f "${GCS_LOCK_FILE}" ]; then
+        echo "Error: lockfile \"${GCS_LOCK_FILE}\" exists, exiting."
         exit 3
     fi
+    touch "${GCS_LOCK_FILE}"
+    trap cleanup EXIT
+}
 
-    echo "Creating backup in \"${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}\""
-
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
-    if ! [ -d "${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}" ]; then
-        echo "Error: backup \"${GCS_BACKUP_NAME}\" does not exist!"
-        exit 4
-    fi
-
-    echo "Restoring backup from \"${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}\""
-
-fi
-
-touch "${GCS_LOCK_FILE}"
-trap cleanup EXIT
-
-# create an array of modules to execute
-MODULES=()
-
-for i in "${GCS_MODULES_DIR_SYSTEM}/"* "${GCS_MODULES_DIR_LOCAL}/"* "${GCS_MODULES_DIR_USER}/"*; do
-    if [ -x "$i" ]; then
-        MODULE_NAME="${i##/*/}"
-
-        if ! [ -z "${FORCED_MODULE}" ]; then
-            if ! [ "$MODULE_NAME" == "${FORCED_MODULE}" ]; then
-                continue
-            fi
+function select_action() {
+    if [ "${GCS_ACTION}" == "apply-theme" ]; then
+        if [ -f "${GCS_THEMES_DIR_USER}/${COLOR_THEME_NAME}/colortheme" ]; then true
+        elif  [ -f "${GCS_THEMES_DIR_LOCAL}/${COLOR_THEME_NAME}/colortheme" ]; then true
+        elif  [ -f "${GCS_THEMES_DIR_SYSTEM}/${COLOR_THEME_NAME}/colortheme" ]; then true
+        else
+            echo "Error: theme \"${COLOR_THEME_NAME}\" not found!"
+            exit 2
         fi
 
-        for j in ${!MODULES[@]}; do
-            if [ "${MODULE_NAME}" == "${MODULES[j]##/*/}" ]; then
-                MODULES[$j]=''
-            fi
-        done
-        MODULES+=("$i")
-    fi
-done
+        echo "Applying color theme ${COLOR_THEME_NAME}"
 
-# execute modules
-for module_file in ${MODULES[@]}; do
-    # Load color theme file. It is loaded before each module to prevent modules from modifying the colors.
-    load_color_theme "${COLOR_THEME_NAME}"
-    # Load a module
-    . "${module_file}"
-done
+    elif [ "${GCS_ACTION}" == "create-backup" ]; then
+        if [ -d "${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}" ]; then
+            echo "Error: backup \"${GCS_BACKUP_NAME}\" already exists!"
+            exit 3
+        fi
+
+        echo "Creating backup in \"${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}\""
+
+    elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+        if ! [ -d "${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}" ]; then
+            echo "Error: backup \"${GCS_BACKUP_NAME}\" does not exist!"
+            exit 4
+        fi
+
+        echo "Restoring backup from \"${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}\""
+
+    fi
+}
+
+# create an array of modules to execute
+function select_modules() {
+    MODULES=()
+
+    for i in "${GCS_MODULES_DIR_SYSTEM}/"* "${GCS_MODULES_DIR_LOCAL}/"* "${GCS_MODULES_DIR_USER}/"*; do
+        if [ -x "$i" ]; then
+            MODULE_NAME="${i##/*/}"
+
+            if ! [ -z "${FORCED_MODULE}" ]; then
+                if ! [ "$MODULE_NAME" == "${FORCED_MODULE}" ]; then
+                    continue
+                fi
+            fi
+
+            for j in ${!MODULES[@]}; do
+                if [ "${MODULE_NAME}" == "${MODULES[j]##/*/}" ]; then
+                    MODULES[$j]=''
+                fi
+            done
+            MODULES+=("$i")
+        fi
+    done
+}
+
+function execute_modules() {
+    for module_file in ${MODULES[@]}; do
+        # Load color theme file. It is loaded before each module to prevent modules from modifying the colors.
+        load_color_theme "${COLOR_THEME_NAME}"
+        # Load a module
+        . "${module_file}"
+    done
+}
+
+function main() {
+    initialize_environment
+    parse_options $*
+    lock
+    select_action
+    select_modules
+    execute_modules
+}
+
+main $*
 
diff --git a/src/share/modules/codeblocks b/src/share/modules/codeblocks
--- a/src/share/modules/codeblocks
+++ b/src/share/modules/codeblocks
@@ -1,144 +1,94 @@
 #!/bin/bash
-
 # TODO: set bold font on some styles
 
-which codeblocks >/dev/null || return
+function codeblocks_init_module() {
+    CB_STYLE_CTR=0
+    CB_PREFIX="/CodeBlocksConfig/editor/colour_sets"
+    CB_COLORSET_NAME="${FULL_COLOR_THEME_NAME}"
+    CB_COLORSET_PREFIX="${CB_PREFIX}/${CB_COLORSET_NAME}"
 
-: ${codeblocks_c_default_fg:=${editor_fg}}
-: ${codeblocks_c_default_bg:=${editor_bg}}
-: ${codeblocks_c_selected_fg:=${editor_selected_fg}}
-: ${codeblocks_c_selected_bg:=${editor_selected_bg}}
-: ${codeblocks_c_number:=${editor_number}}
-: ${codeblocks_c_class:=${editor_class}}
-: ${codeblocks_c_string:=${editor_string}}
-: ${codeblocks_c_operator:=${editor_operator}}
-: ${codeblocks_c_comment:=${editor_comment}}
-: ${codeblocks_c_comment_line:=${editor_comment}}
-: ${codeblocks_c_comment_doc:=${editor_comment}}
-: ${codeblocks_c_comment_line_doc:=${editor_comment}}
-: ${codeblocks_c_comment_keyword_doc:=${editor_preprocessor}}
-: ${codeblocks_c_comment_keyword_error_doc:=${editor_error}}
-: ${codeblocks_c_keyword:=${editor_keyword}}
-: ${codeblocks_c_character:=${editor_character}}
-: ${codeblocks_c_preprocessor:=${editor_preprocessor}}
-: ${codeblocks_c_brace_good_fg:=${editor_brace_good}}
-: ${codeblocks_c_brace_good_bg:=${editor_bg}}
-: ${codeblocks_c_current_line:=${editor_current_line_bg}}
+    CODEBLOCKS_ENABLE_DEFAULT="true"
+    CODEBLOCKS_CONFIG_FILE_DEFAULT="$HOME/.config/codeblocks/default.conf"
 
-: ${codeblocks_diff_default_fg:=${editor_fg}}
-: ${codeblocks_diff_default_bg:=${editor_bg}}
-: ${codeblocks_diff_comment:=${editor_comment}}
-: ${codeblocks_diff_command:=${editor_keyword}}
-: ${codeblocks_diff_header:=${editor_preprocessor}}
-: ${codeblocks_diff_position:=${editor_number}}
-: ${codeblocks_diff_deleted:=${editor_diff_removed}}
-: ${codeblocks_diff_added:=${editor_diff_added}}
+    CODEBLOCKS_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} codeblocks enable      2>/dev/null || echo "${CODEBLOCKS_ENABLE_DEFAULT}")"
+    CODEBLOCKS_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} codeblocks config_file 2>/dev/null || echo "${CODEBLOCKS_CONFIG_FILE_DEFAULT}")"
 
-: ${codeblocks_active_caption_colour:=${titlebar_focused_bg_color}}
-: ${codeblocks_active_caption_gradient_colour:=${titlebar_focused_bg_color}}
-: ${codeblocks_active_caption_text_colour:=${titlebar_focused_fg_color}}
-: ${codeblocks_inactive_caption_colour:=${titlebar_unfocused_bg_color}}
-: ${codeblocks_inactive_caption_gradient_colour:=${titlebar_unfocused_bg_color}}
-: ${codeblocks_inactive_caption_text_colour:=${titlebar_unfocused_fg_color}}
-: ${codeblocks_project_tree_non_source_files:=${editor_comment}}
-
-: ${codeblocks_editor_margin_chrome:=${editor_frame_bg}}
-: ${codeblocks_editor_margin_chrome_highlight:=${editor_frame_bg}}
-: ${codeblocks_editor_linenumbers_bg:=${editor_frame_bg}}
-: ${codeblocks_editor_linenumbers_fg:=${editor_frame_fg}}
-: ${codeblocks_editor_gutter:=${editor_long_line_marker}}
-
-# declare some constants
-CB_STYLE_CTR=0
-CB_PREFIX="/CodeBlocksConfig/editor/colour_sets"
-CB_COLORSET_NAME="${FULL_COLOR_THEME_NAME}"
-CB_COLORSET_PREFIX="${CB_PREFIX}/${CB_COLORSET_NAME}"
-
-# helper function to set styles in Code::blocks config file
-codeblocks_add_style() {
-
-    if [ "$#" -ne 5 ]; then
-        echo "Error: ${FUNCNAME[0]}() requires 5 arguments!"
-        exit 2
-    fi
-
-    local name="$1"
-    local lang="$2"
-    local fg_color="$3"
-    local bg_color="$4"
-    local file="$5"
-
-    xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}"                           --type elem -n "style${CB_STYLE_CTR}"  "${file}"
-    xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"      --type elem -n "NAME"                  "${file}"
-    xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/NAME" --type elem -n "str" --value "${name}" "${file}"
-
-    if [ "${fg_color}" != "default" ]; then
-        local fg_red="$(   printf "%d" 0x${fg_color:1:2})"
-        local fg_green="$( printf "%d" 0x${fg_color:3:2})"
-        local fg_blue="$(  printf "%d" 0x${fg_color:5:2})"
-        
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"             --type elem -n "FORE"                         "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE"        --type elem -n "colour"                       "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "r"      --value "${fg_red}"   "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "g"      --value "${fg_green}" "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "b"      --value "${fg_blue}"  "${file}"
-    fi
-
-    if [ "${bg_color}" != "default" ]; then
-    #xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"
-    #else
-        local bg_red="$(   printf "%d" 0x${bg_color:1:2})"
-        local bg_green="$( printf "%d" 0x${bg_color:3:2})"
-        local bg_blue="$(  printf "%d" 0x${bg_color:5:2})"
-        
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"             --type elem -n "BACK"                         "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"        --type elem -n "colour"                       "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "r"      --value "${bg_red}"   "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "g"      --value "${bg_green}" "${file}"
-        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "b"      --value "${bg_blue}"  "${file}"
-    fi
-
-    CB_STYLE_CTR="$(expr $CB_STYLE_CTR + 1)"
+    GCS_SYNTAX_FALLBACK_DEFAULT="true"
+    GCS_SYNTAX_FALLBACK="$(crudini        --get ${GCS_CONFIG_FILE} gcs        syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK_DEFAULT}")"
+    CODEBLOCKS_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} codeblocks syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK}")"
 }
 
-# helper function to set colors outside colorsets
-codeblocks_set_color (){
 
-    if [ "$#" -ne 3 ]; then
-        echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
-        exit 2
+
+function codeblocks_check_dependencies() {
+    if ! which codeblocks >/dev/null; then
+        return 1
+
+    elif ! [ "${CODEBLOCKS_ENABLE}" == "true" ]; then
+        printf "* Ignoring Code::Blocks (disabled from configuration).\n"
+        return 1
+
+    elif ! [ -f "${CODEBLOCKS_CONFIG_FILE}" ]; then
+        printf "* Ignoring Code::Blocks (configuration file ${CODEBLOCKS_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
     fi
-
-    local path="$1"
-    local color="$2"
-    local file="$3"
-
-    local red="$(   printf "%d" 0x${color:1:2})"
-    local green="$( printf "%d" 0x${color:3:2})"
-    local blue="$(  printf "%d" 0x${color:5:2})"
-
-    xmlstarlet ed --inplace --update "${path}/colour/@r" --value "${red}"   "${file}"
-    xmlstarlet ed --inplace --update "${path}/colour/@g" --value "${green}" "${file}"
-    xmlstarlet ed --inplace --update "${path}/colour/@b" --value "${blue}"  "${file}"
 }
 
-CODEBLOCKS_ENABLE_DEFAULT="true"
-CODEBLOCKS_CONFIG_FILE_DEFAULT="$HOME/.config/codeblocks/default.conf"
 
-CODEBLOCKS_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} codeblocks enable      2>/dev/null || echo "${CODEBLOCKS_ENABLE_DEFAULT}")"
-CODEBLOCKS_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} codeblocks config_file 2>/dev/null || echo "${CODEBLOCKS_CONFIG_FILE_DEFAULT}")"
 
-GCS_SYNTAX_FALLBACK_DEFAULT="true"
-GCS_SYNTAX_FALLBACK="$(crudini        --get ${GCS_CONFIG_FILE} gcs        syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK_DEFAULT}")"
-CODEBLOCKS_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} codeblocks syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK}")"
+function codeblocks_derive_colors() {
+    : ${codeblocks_c_default_fg:=${editor_fg}}
+    : ${codeblocks_c_default_bg:=${editor_bg}}
+    : ${codeblocks_c_selected_fg:=${editor_selected_fg}}
+    : ${codeblocks_c_selected_bg:=${editor_selected_bg}}
+    : ${codeblocks_c_number:=${editor_number}}
+    : ${codeblocks_c_class:=${editor_class}}
+    : ${codeblocks_c_string:=${editor_string}}
+    : ${codeblocks_c_operator:=${editor_operator}}
+    : ${codeblocks_c_comment:=${editor_comment}}
+    : ${codeblocks_c_comment_line:=${editor_comment}}
+    : ${codeblocks_c_comment_doc:=${editor_comment}}
+    : ${codeblocks_c_comment_line_doc:=${editor_comment}}
+    : ${codeblocks_c_comment_keyword_doc:=${editor_preprocessor}}
+    : ${codeblocks_c_comment_keyword_error_doc:=${editor_error}}
+    : ${codeblocks_c_keyword:=${editor_keyword}}
+    : ${codeblocks_c_character:=${editor_character}}
+    : ${codeblocks_c_preprocessor:=${editor_preprocessor}}
+    : ${codeblocks_c_brace_good_fg:=${editor_brace_good}}
+    : ${codeblocks_c_brace_good_bg:=${editor_bg}}
+    : ${codeblocks_c_current_line:=${editor_current_line_bg}}
 
-if ! [ "${CODEBLOCKS_ENABLE}" == "true" ]; then
-    printf "* Ignoring Code::Blocks (disabled from configuration).\n"
+    : ${codeblocks_diff_default_fg:=${editor_fg}}
+    : ${codeblocks_diff_default_bg:=${editor_bg}}
+    : ${codeblocks_diff_comment:=${editor_comment}}
+    : ${codeblocks_diff_command:=${editor_keyword}}
+    : ${codeblocks_diff_header:=${editor_preprocessor}}
+    : ${codeblocks_diff_position:=${editor_number}}
+    : ${codeblocks_diff_deleted:=${editor_diff_removed}}
+    : ${codeblocks_diff_added:=${editor_diff_added}}
 
-elif ! [ -f "${CODEBLOCKS_CONFIG_FILE}" ]; then
-    printf "* Ignoring Code::Blocks (configuration file not found: ${CODEBLOCKS_CONFIG_FILE}).\n"
+    : ${codeblocks_active_caption_colour:=${titlebar_focused_bg_color}}
+    : ${codeblocks_active_caption_gradient_colour:=${titlebar_focused_bg_color}}
+    : ${codeblocks_active_caption_text_colour:=${titlebar_focused_fg_color}}
+    : ${codeblocks_inactive_caption_colour:=${titlebar_unfocused_bg_color}}
+    : ${codeblocks_inactive_caption_gradient_colour:=${titlebar_unfocused_bg_color}}
+    : ${codeblocks_inactive_caption_text_colour:=${titlebar_unfocused_fg_color}}
+    : ${codeblocks_project_tree_non_source_files:=${editor_comment}}
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    : ${codeblocks_editor_margin_chrome:=${editor_frame_bg}}
+    : ${codeblocks_editor_margin_chrome_highlight:=${editor_frame_bg}}
+    : ${codeblocks_editor_linenumbers_bg:=${editor_frame_bg}}
+    : ${codeblocks_editor_linenumbers_fg:=${editor_frame_fg}}
+    : ${codeblocks_editor_gutter:=${editor_long_line_marker}}
+}
+
+
+
+function codeblocks_create_backup() {
     printf "* Making backup of Code::Blocks configuration file..."
 
     CODEBLOCKS_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/codeblocks"
@@ -146,8 +96,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${CODEBLOCKS_CONFIG_FILE}" "${CODEBLOCKS_BACKUP_DIR}/default.conf"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function codeblocks_restore_backup() {
     printf "* Restoring backup of Code::Blocks configuration file..."
 
     CODEBLOCKS_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/codeblocks"
@@ -157,8 +110,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function codeblocks_apply_theme() {
     if [ "${editor_syntax_enable}" == "false" ]; then
         if [ "${CODEBLOCKS_SYNTAX_FALLBACK}" == "true" ]; then
             if [ "$(xmlstarlet sel -t -v "${CB_PREFIX}/ACTIVE_COLOUR_SET/str" "${CODEBLOCKS_CONFIG_FILE}")" == "${CB_COLORSET_NAME}" ]; then
@@ -246,6 +202,95 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
         printf " done.\n"
 
     fi
+}
+
+
+
+# helper function to set styles in Code::blocks config file
+function codeblocks_add_style() {
+
+    if [ "$#" -ne 5 ]; then
+        echo "Error: ${FUNCNAME[0]}() requires 5 arguments!"
+        exit 2
+    fi
+
+    local name="$1"
+    local lang="$2"
+    local fg_color="$3"
+    local bg_color="$4"
+    local file="$5"
+
+    xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}"                           --type elem -n "style${CB_STYLE_CTR}"  "${file}"
+    xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"      --type elem -n "NAME"                  "${file}"
+    xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/NAME" --type elem -n "str" --value "${name}" "${file}"
+
+    if [ "${fg_color}" != "default" ]; then
+        local fg_red="$(   printf "%d" 0x${fg_color:1:2})"
+        local fg_green="$( printf "%d" 0x${fg_color:3:2})"
+        local fg_blue="$(  printf "%d" 0x${fg_color:5:2})"
+        
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"             --type elem -n "FORE"                         "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE"        --type elem -n "colour"                       "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "r"      --value "${fg_red}"   "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "g"      --value "${fg_green}" "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/FORE/colour" --type attr -n "b"      --value "${fg_blue}"  "${file}"
+    fi
+
+    if [ "${bg_color}" != "default" ]; then
+    #xmlstarlet ed --inplace --delete "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"
+    #else
+        local bg_red="$(   printf "%d" 0x${bg_color:1:2})"
+        local bg_green="$( printf "%d" 0x${bg_color:3:2})"
+        local bg_blue="$(  printf "%d" 0x${bg_color:5:2})"
+        
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}"             --type elem -n "BACK"                         "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK"        --type elem -n "colour"                       "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "r"      --value "${bg_red}"   "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "g"      --value "${bg_green}" "${file}"
+        xmlstarlet ed --inplace --subnode "${CB_COLORSET_PREFIX}/${lang}/style${CB_STYLE_CTR}/BACK/colour" --type attr -n "b"      --value "${bg_blue}"  "${file}"
+    fi
+
+    CB_STYLE_CTR="$(expr $CB_STYLE_CTR + 1)"
+}
+
+
+
+# helper function to set colors outside colorsets
+function codeblocks_set_color (){
+
+    if [ "$#" -ne 3 ]; then
+        echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
+        exit 2
+    fi
+
+    local path="$1"
+    local color="$2"
+    local file="$3"
+
+    local red="$(   printf "%d" 0x${color:1:2})"
+    local green="$( printf "%d" 0x${color:3:2})"
+    local blue="$(  printf "%d" 0x${color:5:2})"
+
+    xmlstarlet ed --inplace --update "${path}/colour/@r" --value "${red}"   "${file}"
+    xmlstarlet ed --inplace --update "${path}/colour/@g" --value "${green}" "${file}"
+    xmlstarlet ed --inplace --update "${path}/colour/@b" --value "${blue}"  "${file}"
+}
+
+
+
+codeblocks_init_module
+codeblocks_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    codeblocks_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    codeblocks_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    codeblocks_derive_colors
+    codeblocks_apply_theme
 
 fi
 
diff --git a/src/share/modules/dunst b/src/share/modules/dunst
--- a/src/share/modules/dunst
+++ b/src/share/modules/dunst
@@ -1,30 +1,50 @@
 #!/bin/bash
 
-which dunst >/dev/null || return
+function dunst_init_module() {
+    DUNST_ENABLE_DEFAULT="true"
+    DUNST_CONFIG_FILE_DEFAULT="$HOME/.config/dunst/dunstrc"
+    DUNST_RESTART_COMMAND_DEFAULT=""
 
-DUNST_ENABLE_DEFAULT="true"
-DUNST_CONFIG_FILE_DEFAULT="$HOME/.config/dunst/dunstrc"
-DUNST_RESTART_COMMAND_DEFAULT=""
+    DUNST_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} dunst enable          2>/dev/null || echo "${DUNST_ENABLE_DEFAULT}")"
+    DUNST_CONFIG_FILE="$(crudini     --get ${GCS_CONFIG_FILE} dunst config_file     2>/dev/null || echo "${DUNST_CONFIG_FILE_DEFAULT}")"
+    DUNST_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} dunst restart_command 2>/dev/null || echo "${DUNST_RESTART_COMMAND_DEFAULT}")"
+}
 
-DUNST_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} dunst enable          2>/dev/null || echo "${DUNST_ENABLE_DEFAULT}")"
-DUNST_CONFIG_FILE="$(crudini     --get ${GCS_CONFIG_FILE} dunst config_file     2>/dev/null || echo "${DUNST_CONFIG_FILE_DEFAULT}")"
-DUNST_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} dunst restart_command 2>/dev/null || echo "${DUNST_RESTART_COMMAND_DEFAULT}")"
 
-: ${dunst_frame:=${selected_bg_color}}
-: ${dunst_urgency_low_bg:=${notification_bg_color}}
-: ${dunst_urgency_low_fg:=${notification_fg_color}}
-: ${dunst_urgency_normal_bg:=${selected_bg_color}}
-: ${dunst_urgency_normal_fg:=${selected_fg_color}}
-: ${dunst_urgency_critical_bg:=${titlebar_urgent_bg_color}}
-: ${dunst_urgency_critical_fg:=${selected_fg_color}}
 
-if ! [ "${DUNST_ENABLE}" == "true" ]; then
-    printf "* Ignoring dunst (disabled from configuration).\n"
+function dunst_check_dependencies() {
+    if ! which dunst >/dev/null; then
+        return 1
 
-elif ! [ -f "${DUNST_CONFIG_FILE}" ]; then
-    printf "* Ignoring dunst (configuration file \"${DUNST_CONFIG_FILE}\" not found).\n"
+    elif ! [ "${DUNST_ENABLE}" == "true" ]; then
+        printf "* Ignoring dunst (disabled from configuration).\n"
+        return 1
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    elif ! [ -f "${DUNST_CONFIG_FILE}" ]; then
+        printf "* Ignoring dunst (configuration file ${DUNST_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
+    fi
+}
+
+
+
+function dunst_derive_colors() {
+    : ${dunst_frame:=${selected_bg_color}}
+    : ${dunst_urgency_low_bg:=${notification_bg_color}}
+    : ${dunst_urgency_low_fg:=${notification_fg_color}}
+    : ${dunst_urgency_normal_bg:=${selected_bg_color}}
+    : ${dunst_urgency_normal_fg:=${selected_fg_color}}
+    : ${dunst_urgency_critical_bg:=${titlebar_urgent_bg_color}}
+    : ${dunst_urgency_critical_fg:=${selected_fg_color}}
+}
+
+
+
+function dunst_create_backup() {
     printf "* Making backup of dunst configuration file..."
 
     DUNST_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/dunst"
@@ -32,8 +52,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${DUNST_CONFIG_FILE}" "${DUNST_BACKUP_DIR}/dunstrc"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function dunst_restore_backup() {
     printf "* Restoring backup of dunst configuration file..."
 
     DUNST_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/dunst"
@@ -46,8 +69,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function dunst_apply_theme() {
     printf "* Setting colors for dunst..."
 
     DUNST_TMP_DIR="${GCS_TMP_DIR}/dunst"
@@ -68,6 +94,23 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
     $DUNST_RESTART_COMMAND &>/dev/null
 
     printf " done.\n"
+}
+
+
+
+dunst_init_module
+dunst_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    dunst_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    dunst_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    dunst_derive_colors
+    dunst_apply_theme
 
 fi
 
diff --git a/src/share/modules/galculator b/src/share/modules/galculator
--- a/src/share/modules/galculator
+++ b/src/share/modules/galculator
@@ -1,26 +1,46 @@
 #!/bin/bash
 
-which galculator >/dev/null || return
+function galculator_init_module() {
+    GALCULATOR_ENABLE_DEFAULT="true"
+    GALCULATOR_CONFIG_FILE_DEFAULT="$HOME/.config/galculator/galculator.conf"
 
-: ${galculator_bg_color:=${base_color}}
-: ${galculator_result_color:=${text_color}}
-: ${galculator_stack_color:=${text_color}}
-: ${galculator_module_active_color:=${selected_bg_color}}
-: ${galculator_module_inactive_color:=${unfocused_text_color}}
+    GALCULATOR_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} galculator enable      2>/dev/null || echo "${GALCULATOR_ENABLE_DEFAULT}")"
+    GALCULATOR_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} galculator config_file 2>/dev/null || echo "${GALCULATOR_CONFIG_FILE_DEFAULT}")"
+}
 
-GALCULATOR_ENABLE_DEFAULT="true"
-GALCULATOR_CONFIG_FILE_DEFAULT="$HOME/.config/galculator/galculator.conf"
 
-GALCULATOR_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} galculator enable      2>/dev/null || echo "${GALCULATOR_ENABLE_DEFAULT}")"
-GALCULATOR_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} galculator config_file 2>/dev/null || echo "${GALCULATOR_CONFIG_FILE_DEFAULT}")"
 
-if ! [ "${GALCULATOR_ENABLE}" == "true" ]; then
-    printf "* Ignoring Galculator (disabled from configuration).\n"
+function galculator_check_dependencies() {
+    if ! which galculator >/dev/null; then
+        return 1
 
-elif ! [ -f "${GALCULATOR_CONFIG_FILE}" ]; then
-    printf "* Ignoring Galculator (config file \"${GALCULATOR_CONFIG_FILE}\" not found).\n"
+    elif ! [ "${GALCULATOR_ENABLE}" == "true" ]; then
+        printf "* Ignoring Galculator (disabled from configuration).\n"
+        return 1
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    elif ! [ -f "${GALCULATOR_CONFIG_FILE}" ]; then
+        printf "* Ignoring Galculator (configuration file ${GALCULATOR_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
+    fi
+}
+
+
+
+function galculator_derive_colors() {
+    : ${galculator_bg_color:=${base_color}}
+    : ${galculator_result_color:=${text_color}}
+    : ${galculator_stack_color:=${text_color}}
+    : ${galculator_module_active_color:=${selected_bg_color}}
+    : ${galculator_module_inactive_color:=${unfocused_text_color}}
+}
+
+
+
+function galculator_create_backup() {
     printf "* Making backup of Galculator configuration file..."
 
     GALCULATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/galculator"
@@ -28,8 +48,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${GALCULATOR_CONFIG_FILE}" "${GALCULATOR_BACKUP_DIR}/galculator.conf"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function galculator_restore_backup() {
     printf "* Restoring backup of Galculator configuration file..."
 
     GALCULATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/galculator"
@@ -39,8 +62,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function galculator_apply_theme() {
     printf "* Setting colors for Galculator..."
 
     GALCULATOR_TMP_DIR="${GCS_TMP_DIR}/galculator"
@@ -57,6 +83,23 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
     mv "${GALCULATOR_TMP_CONFIG_FILE}" "${GALCULATOR_CONFIG_FILE}"
 
     printf " done.\n"
+}
+
+
+
+galculator_init_module
+galculator_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    galculator_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    galculator_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    galculator_derive_colors
+    galculator_apply_theme
 
 fi
 
diff --git a/src/share/modules/geany b/src/share/modules/geany
--- a/src/share/modules/geany
+++ b/src/share/modules/geany
@@ -1,64 +1,84 @@
 #!/bin/bash
 
-which geany >/dev/null || return
+function geany_init_module() {
+    GEANY_ENABLE_DEFAULT="true"
+    GEANY_CONFIG_FILE_DEFAULT="$HOME/.config/geany/geany.conf"
 
-: ${geany_bg:=${editor_bg}}
-: ${geany_fg:=${editor_fg}}
-: ${geany_selected_bg:=${editor_selected_bg}}
-: ${geany_selected_fg:=${editor_selected_fg}}
-: ${geany_frame_bg:=${editor_frame_bg}}
-: ${geany_frame_fg:=${editor_frame_fg}}
-: ${geany_current_line_bg:=${editor_current_line_bg}}
-: ${geany_indent_guide:=${editor_indent_guide}}
+    GEANY_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} geany enable      2>/dev/null || echo "${GEANY_ENABLE_DEFAULT}")"
+    GEANY_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} geany config_file 2>/dev/null || echo "${GEANY_CONFIG_FILE_DEFAULT}")"
 
-: ${geany_number:=${editor_number}}
-: ${geany_class:=${editor_class}}
-: ${geany_string:=${editor_string}}
-: ${geany_operator:=${editor_operator}}
-: ${geany_comment:=${editor_comment}}
-: ${geany_error:=${editor_error}}
-: ${geany_keyword:=${editor_keyword}}
-: ${geany_character:=${editor_character}}
-: ${geany_preprocessor:=${editor_preprocessor}}
-: ${geany_brace_good:=${editor_brace_good}}
-: ${geany_white_space:=${editor_white_space}}
+    GCS_SYNTAX_FALLBACK_DEFAULT="true"
+    GCS_SYNTAX_FALLBACK="$(crudini   --get ${GCS_CONFIG_FILE} gcs   syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK_DEFAULT}")"
+    GEANY_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} geany syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK}")"
+}
 
-: ${geany_margin_folding_bg:=${editor_frame_bg}}
-: ${geany_margin_folding_fg:=${editor_frame_fg}}
-: ${geany_fold_symbol_highlight:=${editor_frame_bg}}
-: ${geany_marker_search_bg:=${editor_selected_bg}}
-: ${geany_marker_search_fg:=${editor_selected_fg}}
-: ${geany_marker_mark_bg:=${editor_frame_bg}}
-: ${geany_marker_mark_fg:=${editor_frame_fg}}
-: ${geany_type:=${editor_section_header}}
-: ${geany_function_bg:=${editor_bg}}
-: ${geany_function_fg:=${editor_class}}
-: ${geany_parameter_bg:=${editor_bg}}
-: ${geany_parameter_fg:=${editor_class}}
-: ${geany_here_doc_bg:=${editor_bg}}
-: ${geany_here_doc_fg:=${editor_string}}
 
-: ${geany_diff_added:=${editor_diff_added}}
-: ${geany_diff_removed:=${editor_diff_removed}}
-: ${geany_diff_changed:=${editor_diff_changed}}
 
-GEANY_ENABLE_DEFAULT="true"
-GEANY_CONFIG_FILE_DEFAULT="$HOME/.config/geany/geany.conf"
+function geany_check_dependencies() {
+    if ! which geany >/dev/null; then
+        return 1
 
-GEANY_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} geany enable      2>/dev/null || echo "${GEANY_ENABLE_DEFAULT}")"
-GEANY_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} geany config_file 2>/dev/null || echo "${GEANY_CONFIG_FILE_DEFAULT}")"
+    elif ! [ "${GEANY_ENABLE}" == "true" ]; then
+        printf "* Ignoring Geany (disabled from configuration).\n"
+        return 1
 
-GCS_SYNTAX_FALLBACK_DEFAULT="true"
-GCS_SYNTAX_FALLBACK="$(crudini   --get ${GCS_CONFIG_FILE} gcs   syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK_DEFAULT}")"
-GEANY_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} geany syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK}")"
+    elif ! [ -f "${GEANY_CONFIG_FILE}" ]; then
+        printf "* Ignoring Geany (configuration file ${GEANY_CONFIG_FILE} not found).\n"
+        return 1
 
-if ! [ "${GEANY_ENABLE}" == "true" ]; then
-    printf "* Ignoring Geany (disabled from configuration).\n"
+    else
+        return 0
 
-elif ! [ -f "${GEANY_CONFIG_FILE}" ]; then
-    printf "* Ignoring Geany (configuration file \"${GEANY_CONFIG_FILE}\" not found).\n"
+    fi
+}
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+
+
+function geany_derive_colors() {
+    : ${geany_bg:=${editor_bg}}
+    : ${geany_fg:=${editor_fg}}
+    : ${geany_selected_bg:=${editor_selected_bg}}
+    : ${geany_selected_fg:=${editor_selected_fg}}
+    : ${geany_frame_bg:=${editor_frame_bg}}
+    : ${geany_frame_fg:=${editor_frame_fg}}
+    : ${geany_current_line_bg:=${editor_current_line_bg}}
+    : ${geany_indent_guide:=${editor_indent_guide}}
+
+    : ${geany_number:=${editor_number}}
+    : ${geany_class:=${editor_class}}
+    : ${geany_string:=${editor_string}}
+    : ${geany_operator:=${editor_operator}}
+    : ${geany_comment:=${editor_comment}}
+    : ${geany_error:=${editor_error}}
+    : ${geany_keyword:=${editor_keyword}}
+    : ${geany_character:=${editor_character}}
+    : ${geany_preprocessor:=${editor_preprocessor}}
+    : ${geany_brace_good:=${editor_brace_good}}
+    : ${geany_white_space:=${editor_white_space}}
+
+    : ${geany_margin_folding_bg:=${editor_frame_bg}}
+    : ${geany_margin_folding_fg:=${editor_frame_fg}}
+    : ${geany_fold_symbol_highlight:=${editor_frame_bg}}
+    : ${geany_marker_search_bg:=${editor_selected_bg}}
+    : ${geany_marker_search_fg:=${editor_selected_fg}}
+    : ${geany_marker_mark_bg:=${editor_frame_bg}}
+    : ${geany_marker_mark_fg:=${editor_frame_fg}}
+    : ${geany_type:=${editor_section_header}}
+    : ${geany_function_bg:=${editor_bg}}
+    : ${geany_function_fg:=${editor_class}}
+    : ${geany_parameter_bg:=${editor_bg}}
+    : ${geany_parameter_fg:=${editor_class}}
+    : ${geany_here_doc_bg:=${editor_bg}}
+    : ${geany_here_doc_fg:=${editor_string}}
+
+    : ${geany_diff_added:=${editor_diff_added}}
+    : ${geany_diff_removed:=${editor_diff_removed}}
+    : ${geany_diff_changed:=${editor_diff_changed}}
+}
+
+
+
+function geany_create_backup() {
     printf "* Making backup of Geany configuration file..."
 
     GEANY_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/geany"
@@ -66,8 +86,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${GEANY_CONFIG_FILE}" "${GEANY_BACKUP_DIR}/geany.conf"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function geany_restore_backup() {
     printf "* Restoring backup of Geany configuration file..."
 
     GEANY_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/geany"
@@ -77,8 +100,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function geany_apply_theme() {
     if [ "${editor_syntax_enable}" == "false" ]; then
         if [ "${GEANY_SYNTAX_FALLBACK}" == "true" ]; then
             printf "* Setting default colors for Geany..."
@@ -164,6 +190,24 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
         fi
 
     fi
+}
+
+
+
+geany_init_module
+geany_check_dependencies
+[ $? == 1 ] && return
+
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    geany_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    geany_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    geany_derive_colors
+    geany_apply_theme
 
 fi
 
diff --git a/src/share/modules/i3wm b/src/share/modules/i3wm
--- a/src/share/modules/i3wm
+++ b/src/share/modules/i3wm
@@ -1,71 +1,88 @@
 #!/bin/bash
 # FIXME: sed gives errors if the relevant lines have also commented copies
 
-which i3 >/dev/null || return
+function i3wm_init_module() {
+    I3_ENABLE_DEFAULT="true"
+    I3_CONFIG_FILE_DEFAULT="$HOME/.config/i3/config"
+    I3_RESTART_COMMAND_DEFAULT="i3-msg restart"
 
-: ${i3_client_focused_border:=${titlebar_focused_bg_color}}
-: ${i3_client_focused_bg:=${titlebar_focused_bg_color}}
-: ${i3_client_focused_fg:=${titlebar_focused_fg_color}}
-: ${i3_client_focused_indicator:=${titlebar_focused_bg_color}}
+    I3_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} i3wm enable          2>/dev/null || echo "${I3_ENABLE_DEFAULT}")"
+    I3_CONFIG_FILE="$(crudini     --get ${GCS_CONFIG_FILE} i3wm config_file     2>/dev/null || echo "${I3_CONFIG_FILE_DEFAULT}")"
+    I3_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} i3wm restart_command 2>/dev/null || echo "${I3_RESTART_COMMAND_DEFAULT}")"
+}
 
-: ${i3_client_focused_inactive_border:=${titlebar_unfocused_bg_color}}
-: ${i3_client_focused_inactive_bg:=${titlebar_unfocused_bg_color}}
-: ${i3_client_focused_inactive_fg:=${titlebar_unfocused_fg_color}}
-: ${i3_client_focused_inactive_indicator:=${titlebar_unfocused_bg_color}}
 
-: ${i3_client_unfocused_border:=${titlebar_unfocused_bg_color}}
-: ${i3_client_unfocused_bg:=${titlebar_unfocused_bg_color}}
-: ${i3_client_unfocused_fg:=${titlebar_unfocused_fg_color}}
-: ${i3_client_unfocused_indicator:=${titlebar_unfocused_bg_color}}
 
-: ${i3_client_urgent_border:=${titlebar_urgent_bg_color}}
-: ${i3_client_urgent_bg:=${titlebar_urgent_bg_color}}
-: ${i3_client_urgent_fg:=${titlebar_urgent_fg_color}}
-: ${i3_client_urgent_indicator:=${titlebar_urgent_bg_color}}
+function i3wm_check_dependencies() {
+    if ! which i3 >/dev/null; then
+        return 1
 
-: ${i3_client_placeholder_border:=${bg_color}}
-: ${i3_client_placeholder_bg:=${bg_color}}
-: ${i3_client_placeholder_fg:=${fg_color}}
-: ${i3_client_placeholder_indicator:=${bg_color}}
+    elif ! [ "${I3_ENABLE}" == "true" ]; then
+        printf "* Ignoring i3 window manager (disabled from configuration).\n"
+        return 1
 
-: ${i3_bar_separator:=${selected_bg_color}}
-: ${i3_bar_background:=${tray_bg_color}}
-: ${i3_bar_statusline:=${tray_fg_color}}
+    elif ! [ -f "${I3_CONFIG_FILE}" ]; then
+        printf "* Ignoring i3 window manager (configuration file \"${I3_CONFIG_FILE}\" not found).\n"
+        return 1
 
-: ${i3_bar_focused_workspace_border:=${tray_focused_bg_color}}
-: ${i3_bar_focused_workspace_bg:=${tray_focused_bg_color}}
-: ${i3_bar_focused_workspace_fg:=${tray_focused_fg_color}}
+    else
+        return 0
 
-: ${i3_bar_active_workspace_border:=${tray_unfocused_bg_color}}
-: ${i3_bar_active_workspace_bg:=${tray_unfocused_bg_color}}
-: ${i3_bar_active_workspace_fg:=${tray_unfocused_fg_color}}
+    fi
+}
 
-: ${i3_bar_inactive_workspace_border:=${tray_unfocused_bg_color}}
-: ${i3_bar_inactive_workspace_bg:=${tray_unfocused_bg_color}}
-: ${i3_bar_inactive_workspace_fg:=${tray_unfocused_fg_color}}
 
-: ${i3_bar_urgent_workspace_border:=${tray_urgent_bg_color}}
-: ${i3_bar_urgent_workspace_bg:=${tray_urgent_bg_color}}
-: ${i3_bar_urgent_workspace_fg:=${tray_urgent_fg_color}}
 
-I3_ENABLE_DEFAULT="true"
-I3_CONFIG_FILE_DEFAULT="$HOME/.config/i3/config"
-I3_RESTART_COMMAND_DEFAULT="i3-msg restart"
+function i3wm_derive_colors() {
+    : ${i3_client_focused_border:=${titlebar_focused_bg_color}}
+    : ${i3_client_focused_bg:=${titlebar_focused_bg_color}}
+    : ${i3_client_focused_fg:=${titlebar_focused_fg_color}}
+    : ${i3_client_focused_indicator:=${titlebar_focused_bg_color}}
 
-I3_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} i3wm enable          2>/dev/null || echo "${I3_ENABLE_DEFAULT}")"
-I3_CONFIG_FILE="$(crudini     --get ${GCS_CONFIG_FILE} i3wm config_file     2>/dev/null || echo "${I3_CONFIG_FILE_DEFAULT}")"
-I3_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} i3wm restart_command 2>/dev/null || echo "${I3_RESTART_COMMAND_DEFAULT}")"
+    : ${i3_client_focused_inactive_border:=${titlebar_unfocused_bg_color}}
+    : ${i3_client_focused_inactive_bg:=${titlebar_unfocused_bg_color}}
+    : ${i3_client_focused_inactive_fg:=${titlebar_unfocused_fg_color}}
+    : ${i3_client_focused_inactive_indicator:=${titlebar_unfocused_bg_color}}
 
-if ! [ "${I3_ENABLE}" == "true" ]; then
-    printf "* Ignoring i3 window manager (disabled from configuration).\n"
+    : ${i3_client_unfocused_border:=${titlebar_unfocused_bg_color}}
+    : ${i3_client_unfocused_bg:=${titlebar_unfocused_bg_color}}
+    : ${i3_client_unfocused_fg:=${titlebar_unfocused_fg_color}}
+    : ${i3_client_unfocused_indicator:=${titlebar_unfocused_bg_color}}
 
-elif ! [ -f "${I3_CONFIG_FILE}" ]; then
-    printf "* Ignoring i3 window manager (configuration file \"${I3_CONFIG_FILE}\" not found).\n"
+    : ${i3_client_urgent_border:=${titlebar_urgent_bg_color}}
+    : ${i3_client_urgent_bg:=${titlebar_urgent_bg_color}}
+    : ${i3_client_urgent_fg:=${titlebar_urgent_fg_color}}
+    : ${i3_client_urgent_indicator:=${titlebar_urgent_bg_color}}
 
-elif ! i3 --get-socketpath &>/dev/null; then
-    printf "* Not setting colors for i3 window manager (not currently active).\n"
+    : ${i3_client_placeholder_border:=${bg_color}}
+    : ${i3_client_placeholder_bg:=${bg_color}}
+    : ${i3_client_placeholder_fg:=${fg_color}}
+    : ${i3_client_placeholder_indicator:=${bg_color}}
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    : ${i3_bar_separator:=${selected_bg_color}}
+    : ${i3_bar_background:=${tray_bg_color}}
+    : ${i3_bar_statusline:=${tray_fg_color}}
+
+    : ${i3_bar_focused_workspace_border:=${tray_focused_bg_color}}
+    : ${i3_bar_focused_workspace_bg:=${tray_focused_bg_color}}
+    : ${i3_bar_focused_workspace_fg:=${tray_focused_fg_color}}
+
+    : ${i3_bar_active_workspace_border:=${tray_unfocused_bg_color}}
+    : ${i3_bar_active_workspace_bg:=${tray_unfocused_bg_color}}
+    : ${i3_bar_active_workspace_fg:=${tray_unfocused_fg_color}}
+
+    : ${i3_bar_inactive_workspace_border:=${tray_unfocused_bg_color}}
+    : ${i3_bar_inactive_workspace_bg:=${tray_unfocused_bg_color}}
+    : ${i3_bar_inactive_workspace_fg:=${tray_unfocused_fg_color}}
+
+    : ${i3_bar_urgent_workspace_border:=${tray_urgent_bg_color}}
+    : ${i3_bar_urgent_workspace_bg:=${tray_urgent_bg_color}}
+    : ${i3_bar_urgent_workspace_fg:=${tray_urgent_fg_color}}
+}
+
+
+
+function i3wm_create_backup() {
     printf "* Making backup of i3 window manager configuration file..."
 
     I3_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/i3wm"
@@ -73,8 +90,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${I3_CONFIG_FILE}" "${I3_BACKUP_DIR}/config"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function i3wm_restore_backup() {
     printf "* Restoring backup of i3 window manager configuration file..."
 
     I3_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/i3wm"
@@ -87,35 +107,61 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
+
+
+
+function i3wm_apply_theme() {
+    if ! i3 --get-socketpath &>/dev/null; then
+        printf "* Not setting colors for i3 window manager (not currently active).\n"
+
+    else
+
+        printf "* Setting colors for i3 window manager..."
+
+        I3_TMP_DIR="${GCS_TMP_DIR}/i3wm"
+        I3_TMP_CONFIG_FILE="${I3_TMP_DIR}/config"
+        mkdir "${I3_TMP_DIR}"
+        cp "${I3_CONFIG_FILE}" "${I3_TMP_CONFIG_FILE}"
+
+        set_value "client\.focused"          " " "${i3_client_focused_border}          ${i3_client_focused_bg}          ${i3_client_focused_fg}          ${i3_client_focused_indicator}"          "${I3_TMP_CONFIG_FILE}"
+        set_value "client\.focused_inactive" " " "${i3_client_focused_inactive_border} ${i3_client_focused_inactive_bg} ${i3_client_focused_inactive_fg} ${i3_client_focused_inactive_indicator}" "${I3_TMP_CONFIG_FILE}"
+        set_value "client\.unfocused"        " " "${i3_client_unfocused_border}        ${i3_client_unfocused_bg}        ${i3_client_unfocused_fg}        ${i3_client_unfocused_indicator}"        "${I3_TMP_CONFIG_FILE}"
+        set_value "client\.urgent"           " " "${i3_client_urgent_border}           ${i3_client_urgent_bg}           ${i3_client_urgent_fg}           ${i3_client_urgent_indicator}"           "${I3_TMP_CONFIG_FILE}"
+        set_value "client\.placeholder"      " " "${i3_client_placeholder_border}      ${i3_client_placeholder_bg}      ${i3_client_placeholder_fg}      ${i3_client_placeholder_indicator}"      "${I3_TMP_CONFIG_FILE}"
+
+        set_value "separator"  " " " ${i3_bar_separator}"  "${I3_TMP_CONFIG_FILE}"
+        set_value "background" " " " ${i3_bar_background}" "${I3_TMP_CONFIG_FILE}"
+        set_value "statusline" " " " ${i3_bar_statusline}" "${I3_TMP_CONFIG_FILE}"
+
+        set_value "focused_workspace"  " " "${i3_bar_focused_workspace_border}  ${i3_bar_focused_workspace_bg}  ${i3_bar_focused_workspace_fg}"  "${I3_TMP_CONFIG_FILE}"
+        set_value "active_workspace"   " " "${i3_bar_active_workspace_border}   ${i3_bar_active_workspace_bg}   ${i3_bar_active_workspace_fg}"   "${I3_TMP_CONFIG_FILE}"
+        set_value "inactive_workspace" " " "${i3_bar_inactive_workspace_border} ${i3_bar_inactive_workspace_bg} ${i3_bar_inactive_workspace_fg}" "${I3_TMP_CONFIG_FILE}"
+        set_value "urgent_workspace"   " " "${i3_bar_urgent_workspace_border}   ${i3_bar_urgent_workspace_bg}   ${i3_bar_urgent_workspace_fg}"   "${I3_TMP_CONFIG_FILE}"
+
+        mv "${I3_TMP_CONFIG_FILE}" "${I3_CONFIG_FILE}"
+
+        ${I3_RESTART_COMMAND} &>/dev/null
+
+        printf " done.\n"
+    fi
+}
+
+
+
+i3wm_init_module
+i3wm_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    i3wm_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    i3wm_restore_backup
 
 elif [ "${GCS_ACTION}" == "apply-theme" ]; then
-    printf "* Setting colors for i3 window manager..."
-
-    I3_TMP_DIR="${GCS_TMP_DIR}/i3wm"
-    I3_TMP_CONFIG_FILE="${I3_TMP_DIR}/config"
-    mkdir "${I3_TMP_DIR}"
-    cp "${I3_CONFIG_FILE}" "${I3_TMP_CONFIG_FILE}"
-
-    set_value "client\.focused"          " " "${i3_client_focused_border}          ${i3_client_focused_bg}          ${i3_client_focused_fg}          ${i3_client_focused_indicator}"          "${I3_TMP_CONFIG_FILE}"
-    set_value "client\.focused_inactive" " " "${i3_client_focused_inactive_border} ${i3_client_focused_inactive_bg} ${i3_client_focused_inactive_fg} ${i3_client_focused_inactive_indicator}" "${I3_TMP_CONFIG_FILE}"
-    set_value "client\.unfocused"        " " "${i3_client_unfocused_border}        ${i3_client_unfocused_bg}        ${i3_client_unfocused_fg}        ${i3_client_unfocused_indicator}"        "${I3_TMP_CONFIG_FILE}"
-    set_value "client\.urgent"           " " "${i3_client_urgent_border}           ${i3_client_urgent_bg}           ${i3_client_urgent_fg}           ${i3_client_urgent_indicator}"           "${I3_TMP_CONFIG_FILE}"
-    set_value "client\.placeholder"      " " "${i3_client_placeholder_border}      ${i3_client_placeholder_bg}      ${i3_client_placeholder_fg}      ${i3_client_placeholder_indicator}"      "${I3_TMP_CONFIG_FILE}"
-
-    set_value "separator"  " " " ${i3_bar_separator}"  "${I3_TMP_CONFIG_FILE}"
-    set_value "background" " " " ${i3_bar_background}" "${I3_TMP_CONFIG_FILE}"
-    set_value "statusline" " " " ${i3_bar_statusline}" "${I3_TMP_CONFIG_FILE}"
-
-    set_value "focused_workspace"  " " "${i3_bar_focused_workspace_border}  ${i3_bar_focused_workspace_bg}  ${i3_bar_focused_workspace_fg}"  "${I3_TMP_CONFIG_FILE}"
-    set_value "active_workspace"   " " "${i3_bar_active_workspace_border}   ${i3_bar_active_workspace_bg}   ${i3_bar_active_workspace_fg}"   "${I3_TMP_CONFIG_FILE}"
-    set_value "inactive_workspace" " " "${i3_bar_inactive_workspace_border} ${i3_bar_inactive_workspace_bg} ${i3_bar_inactive_workspace_fg}" "${I3_TMP_CONFIG_FILE}"
-    set_value "urgent_workspace"   " " "${i3_bar_urgent_workspace_border}   ${i3_bar_urgent_workspace_bg}   ${i3_bar_urgent_workspace_fg}"   "${I3_TMP_CONFIG_FILE}"
-
-    mv "${I3_TMP_CONFIG_FILE}" "${I3_CONFIG_FILE}"
-
-    ${I3_RESTART_COMMAND} &>/dev/null
-
-    printf " done.\n"
+    i3wm_derive_colors
+    i3wm_apply_theme
 
 fi
 
diff --git a/src/share/modules/lxterminal b/src/share/modules/lxterminal
--- a/src/share/modules/lxterminal
+++ b/src/share/modules/lxterminal
@@ -1,23 +1,43 @@
 #!/bin/bash
 
-which lxterminal >/dev/null || return
+function lxterminal_init_module() {
+    LXTERMINAL_ENABLE_DEFAULT="true"
+    LXTERMINAL_CONFIG_FILE_DEFAULT="$HOME/.config/lxterminal/lxterminal.conf"
 
-: ${lxterminal_bg_color:=${terminal_bg_color}}
-: ${lxterminal_fg_color:=${terminal_fg_color}}
+    LXTERMINAL_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} lxterminal enable      2>/dev/null || echo "${LXTERMINAL_ENABLE_DEFAULT}")"
+    LXTERMINAL_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} lxterminal config_file 2>/dev/null || echo "${LXTERMINAL_CONFIG_FILE_DEFAULT}")"
+}
 
-LXTERMINAL_ENABLE_DEFAULT="true"
-LXTERMINAL_CONFIG_FILE_DEFAULT="$HOME/.config/lxterminal/lxterminal.conf"
 
-LXTERMINAL_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} lxterminal enable      2>/dev/null || echo "${LXTERMINAL_ENABLE_DEFAULT}")"
-LXTERMINAL_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} lxterminal config_file 2>/dev/null || echo "${LXTERMINAL_CONFIG_FILE_DEFAULT}")"
 
-if ! [ "${LXTERMINAL_ENABLE}" == "true" ]; then
-    printf "* Ignoring LXTerminal (disabled from configuration).\n"
+function lxterminal_check_dependencies() {
+    if ! which lxterminal >/dev/null; then
+        return 1
 
-elif ! [ -f "${LXTERMINAL_CONFIG_FILE}" ]; then
-    printf "* Ignoring LXTerminal (configuration file \"${LXTERMINAL_CONFIG_FILE}\" not found).\n"
+    elif ! [ "${LXTERMINAL_ENABLE}" == "true" ]; then
+        printf "* Ignoring LXTerminal (disabled from configuration).\n"
+        return 1
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    elif ! [ -f "${LXTERMINAL_CONFIG_FILE}" ]; then
+        printf "* Ignoring LXTerminal (configuration file ${LXTERMINAL_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
+    fi
+}
+
+
+
+function lxterminal_derive_colors() {
+    : ${lxterminal_bg_color:=${terminal_bg_color}}
+    : ${lxterminal_fg_color:=${terminal_fg_color}}
+}
+
+
+
+function lxterminal_create_backup() {
     printf "* Making backup of LXTerminal configuration file..."
 
     LXTERMINAL_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/lxterminal"
@@ -25,8 +45,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${LXTERMINAL_CONFIG_FILE}" "${LXTERMINAL_BACKUP_DIR}/lxterminal.conf"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function lxterminal_restore_backup() {
     printf "* Restoring backup of LXTerminal configuration file..."
 
     LXTERMINAL_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/lxterminal"
@@ -36,8 +59,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function lxterminal_apply_theme() {
     printf "* Setting colors for LXTerminal..."
 
     LXTERMINAL_TMP_DIR="${GCS_TMP_DIR}/lxterminal"
@@ -51,6 +77,23 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
     mv "${LXTERMINAL_TMP_CONFIG_FILE}" "${LXTERMINAL_CONFIG_FILE}"
 
     printf " done.\n"
+}
+
+
+
+lxterminal_init_module
+lxterminal_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    lxterminal_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    lxterminal_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    lxterminal_derive_colors
+    lxterminal_apply_theme
 
 fi
 
diff --git a/src/share/modules/qt5ct b/src/share/modules/qt5ct
--- a/src/share/modules/qt5ct
+++ b/src/share/modules/qt5ct
@@ -1,22 +1,42 @@
 #!/bin/bash
 
-which qt5ct >/dev/null || return
+function qt5ct_init_module() {
+    QT5CT_ENABLE_DEFAULT="true"
+    QT5CT_CONFIG_FILE_DEFAULT="$HOME/.config/qt5ct/qt5ct.conf"
 
-: ${qt5ct_icon_theme_name:=${icon_theme_name}}
+    QT5CT_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} qt5ct enable      2>/dev/null || echo "${QT5CT_ENABLE_DEFAULT}")"
+    QT5CT_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} qt5ct config_file 2>/dev/null || echo "${QT5CT_CONFIG_FILE_DEFAULT}")"
+}
 
-QT5CT_ENABLE_DEFAULT="true"
-QT5CT_CONFIG_FILE_DEFAULT="$HOME/.config/qt5ct/qt5ct.conf"
 
-QT5CT_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} qt5ct enable      2>/dev/null || echo "${QT5CT_ENABLE_DEFAULT}")"
-QT5CT_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} qt5ct config_file 2>/dev/null || echo "${QT5CT_CONFIG_FILE_DEFAULT}")"
 
-if ! [ "${QT5CT_ENABLE}" == "true" ]; then
-    printf "* Ignoring qt5ct (disabled from configuration).\n"
+function qt5ct_check_dependencies() {
+    if ! which qt5ct >/dev/null; then
+        return 1
 
-elif ! [ -f "${QT5CT_CONFIG_FILE}" ]; then
-    printf "* Ignoring qt5ct (configuration file \"${QT5CT_CONFIG_FILE}\" not found).\n"
+    elif ! [ "${QT5CT_ENABLE}" == "true" ]; then
+        printf "* Ignoring qt5ct (disabled from configuration).\n"
+        return 1
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    elif ! [ -f "${QT5CT_CONFIG_FILE}" ]; then
+        printf "* Ignoring qt5ct (configuration file ${QT5CT_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
+    fi
+}
+
+
+
+function qt5ct_derive_colors() {
+    : ${qt5ct_icon_theme_name:=${icon_theme_name}}
+}
+
+
+
+function qt5ct_create_backup() {
     printf "* Making backup of qt5ct configuration file..."
 
     QT5CT_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/qt5ct"
@@ -24,8 +44,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${QT5CT_CONFIG_FILE}" "${QT5CT_BACKUP_DIR}/qt5ct.conf"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function qt5ct_restore_backup() {
     printf "* Restoring backup of qt5ct configuration file..."
 
     QT5CT_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/qt5ct"
@@ -35,8 +58,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function qt5ct_apply_theme() {
     printf "* Setting icon theme for qt5..."
 
 
@@ -60,6 +86,23 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
     mv "${QT5CT_TMP_CONFIG_FILE}" "${QT5CT_CONFIG_FILE}"
 
     printf " done.\n"
+}
+
+
+
+qt5ct_init_module
+qt5ct_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    qt5ct_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    qt5ct_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    qt5ct_derive_colors
+    qt5ct_apply_theme
 
 fi
 
diff --git a/src/share/modules/rofi b/src/share/modules/rofi
--- a/src/share/modules/rofi
+++ b/src/share/modules/rofi
@@ -1,40 +1,60 @@
 #!/bin/bash
 
-which rofi >/dev/null || return
+function rofi_init_module() {
+    ROFI_ENABLE_DEFAULT="true"
+    ROFI_CONFIG_FILE_DEFAULT="$HOME/.config/rofi/config"
+    ROFI_RESTART_COMMAND_DEFAULT=""
 
-ROFI_ENABLE_DEFAULT="true"
-ROFI_CONFIG_FILE_DEFAULT="$HOME/.config/rofi/config"
-ROFI_RESTART_COMMAND_DEFAULT=""
+    ROFI_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} rofi enable          2>/dev/null || echo "${ROFI_ENABLE_DEFAULT}")"
+    ROFI_CONFIG_FILE="$(crudini     --get ${GCS_CONFIG_FILE} rofi config_file     2>/dev/null || echo "${ROFI_CONFIG_FILE_DEFAULT}")"
+    ROFI_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} rofi restart_command 2>/dev/null || echo "${ROFI_RESTART_COMMAND_DEFAULT}")"
+}
 
-ROFI_ENABLE="$(crudini          --get ${GCS_CONFIG_FILE} rofi enable          2>/dev/null || echo "${ROFI_ENABLE_DEFAULT}")"
-ROFI_CONFIG_FILE="$(crudini     --get ${GCS_CONFIG_FILE} rofi config_file     2>/dev/null || echo "${ROFI_CONFIG_FILE_DEFAULT}")"
-ROFI_RESTART_COMMAND="$(crudini --get ${GCS_CONFIG_FILE} rofi restart_command 2>/dev/null || echo "${ROFI_RESTART_COMMAND_DEFAULT}")"
 
-: ${rofi_normal_bg:=${base_color}}
-: ${rofi_normal_fg:=${text_color}}
-: ${rofi_normal_bg_alt:=${base_color}}
-: ${rofi_normal_highlight_bg:=${selected_bg_color}}
-: ${rofi_normal_highlight:=${selected_fg_color}}
-: ${rofi_urgent_bg:=${base_color}}
-: ${rofi_urgent_fg:=${text_color}}
-: ${rofi_urgent_bg_alt:=${base_color}}
-: ${rofi_urgent_highlight_bg:=${selected_bg_color}}
-: ${rofi_urgent_highlight:=${selected_fg_color}}
-: ${rofi_active_bg:=${base_color}}
-: ${rofi_active_fg:=${text_color}}
-: ${rofi_active_bg_alt:=${base_color}}
-: ${rofi_active_highlight_bg:=${selected_bg_color}}
-: ${rofi_active_highlight:=${selected_fg_color}}
-: ${rofi_window_bg_border:=${bg_color}}
-: ${rofi_window_separator:=${bg_color}}
 
-if ! [ "${ROFI_ENABLE}" == "true" ]; then
-    printf "* Ignoring rofi (disabled from configuration).\n"
+function rofi_check_dependencies() {
+    if ! which rofi >/dev/null; then
+        return 1
 
-elif ! [ -f "${ROFI_CONFIG_FILE}" ]; then
-    printf "* Ignoring rofi (configuration file \"${ROFI_CONFIG_FILE}\" not found).\n"
+    elif ! [ "${ROFI_ENABLE}" == "true" ]; then
+        printf "* Ignoring rofi (disabled from configuration).\n"
+        return 1
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    elif ! [ -f "${ROFI_CONFIG_FILE}" ]; then
+        printf "* Ignoring rofi (configuration file ${ROFI_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
+    fi
+}
+
+
+
+function rofi_derive_colors() {
+    : ${rofi_normal_bg:=${base_color}}
+    : ${rofi_normal_fg:=${text_color}}
+    : ${rofi_normal_bg_alt:=${base_color}}
+    : ${rofi_normal_highlight_bg:=${selected_bg_color}}
+    : ${rofi_normal_highlight:=${selected_fg_color}}
+    : ${rofi_urgent_bg:=${base_color}}
+    : ${rofi_urgent_fg:=${text_color}}
+    : ${rofi_urgent_bg_alt:=${base_color}}
+    : ${rofi_urgent_highlight_bg:=${selected_bg_color}}
+    : ${rofi_urgent_highlight:=${selected_fg_color}}
+    : ${rofi_active_bg:=${base_color}}
+    : ${rofi_active_fg:=${text_color}}
+    : ${rofi_active_bg_alt:=${base_color}}
+    : ${rofi_active_highlight_bg:=${selected_bg_color}}
+    : ${rofi_active_highlight:=${selected_fg_color}}
+    : ${rofi_window_bg_border:=${bg_color}}
+    : ${rofi_window_separator:=${bg_color}}
+}
+
+
+
+function rofi_create_backup() {
     printf "* Making backup of rofi configuration file..."
 
     ROFI_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/rofi"
@@ -42,8 +62,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${ROFI_CONFIG_FILE}" "${ROFI_BACKUP_DIR}/config"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function rofi_restore_backup() {
     printf "* Restoring backup of rofi configuration file..."
 
     ROFI_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/rofi"
@@ -56,8 +79,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function rofi_apply_theme() {
     printf "* Setting colors for rofi..."
 
     ROFI_TMP_DIR="${GCS_TMP_DIR}/rofi"
@@ -75,6 +101,23 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
     $ROFI_RESTART_COMMAND &>/dev/null
 
     printf " done.\n"
+}
+
+
+
+rofi_init_module
+rofi_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    rofi_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    rofi_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    rofi_derive_colors
+    rofi_apply_theme
 
 fi
 
diff --git a/src/share/modules/terminator b/src/share/modules/terminator
--- a/src/share/modules/terminator
+++ b/src/share/modules/terminator
@@ -1,6 +1,96 @@
 #!/bin/bash
 
-which terminator >/dev/null || return
+function terminator_init_module() {
+    TERMINATOR_ENABLE_DEFAULT="true"
+    TERMINATOR_CONFIG_FILE_DEFAULT="$HOME/.config/terminator/config"
+
+    TERMINATOR_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} terminator enable      2>/dev/null || echo "${TERMINATOR_ENABLE_DEFAULT}")"
+    TERMINATOR_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} terminator config_file 2>/dev/null || echo "${TERMINATOR_CONFIG_FILE_DEFAULT}")"
+}
+
+
+
+function terminator_check_dependencies() {
+    if ! which terminator >/dev/null; then
+        return 1
+
+    elif ! [ "${TERMINATOR_ENABLE}" == "true" ]; then
+        printf "* Ignoring Terminator (disabled from configuration).\n"
+        return 1
+
+    elif ! [ -f "${TERMINATOR_CONFIG_FILE}" ]; then
+        printf "* Ignoring Terminator (configuration file ${TERMINATOR_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
+    fi
+}
+
+
+
+function terminator_derive_colors() {
+    : ${terminator_bg_color:=${terminal_bg_color}}
+    : ${terminator_fg_color:=${terminal_fg_color}}
+    : ${terminator_cursos_color:=${selected_fg_color}}
+    : ${terminator_palette:=${terminal_palette_black}:${terminal_palette_red}:${terminal_palette_green}:${terminal_palette_yellow}:${terminal_palette_blue}:${terminal_palette_purple}:${terminal_palette_cyan}:${terminal_palette_white}:${terminal_palette_light_black}:${terminal_palette_light_red}:${terminal_palette_light_green}:${terminal_palette_light_yellow}:${terminal_palette_light_blue}:${terminal_palette_light_purple}:${terminal_palette_light_cyan}:${terminal_palette_light_white}}
+    : ${terminator_transparency:=${terminal_transparency}}
+}
+
+
+
+function terminator_create_backup() {
+    printf "* Making backup of terminator configuration file..."
+
+    TERMINATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/terminator"
+    mkdir -p "${TERMINATOR_BACKUP_DIR}"
+    cp "${TERMINATOR_CONFIG_FILE}" "${TERMINATOR_BACKUP_DIR}/config"
+
+    printf " done.\n"
+}
+
+
+
+function terminator_restore_backup() {
+    printf "* Restoring backup of terminator configuration file..."
+
+    TERMINATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/terminator"
+    if [ -f "${TERMINATOR_BACKUP_DIR}/config" ]; then
+        cp "${TERMINATOR_BACKUP_DIR}/config" "${TERMINATOR_CONFIG_FILE}"
+        printf " done.\n"
+    else
+        printf " not found!\n"
+    fi
+}
+
+
+
+function terminator_apply_theme() {
+    printf "* Setting colors for terminator..."
+
+    TERMINATOR_TMP_DIR="${GCS_TMP_DIR}/terminator"
+    TERMINATOR_TMP_CONFIG_FILE="${TERMINATOR_TMP_DIR}/config"
+    mkdir "${TERMINATOR_TMP_DIR}"
+    cp "${TERMINATOR_CONFIG_FILE}" "${TERMINATOR_TMP_CONFIG_FILE}"
+
+    terminator_set_value_default_profile "background_color" "${terminal_bg_color}"  "${TERMINATOR_TMP_CONFIG_FILE}"
+    terminator_set_value_default_profile "foreground_color" "${terminal_fg_color}"  "${TERMINATOR_TMP_CONFIG_FILE}"
+    terminator_set_value_default_profile "cursor_color"     "${terminal_fg_color}"  "${TERMINATOR_TMP_CONFIG_FILE}"
+    terminator_set_value_default_profile "palette"          "${terminator_palette}" "${TERMINATOR_TMP_CONFIG_FILE}"
+    if [ "${terminal_transparency}" != "" ]; then
+        terminator_set_value_default_profile "background_type"     "transparent"              "${TERMINATOR_TMP_CONFIG_FILE}"
+        terminator_set_value_default_profile "background_darkness" "${terminal_transparency}" "${TERMINATOR_TMP_CONFIG_FILE}"
+    else
+        terminator_set_value_default_profile "background_type"     "solid"                    "${TERMINATOR_TMP_CONFIG_FILE}"
+    fi
+
+    mv "${TERMINATOR_TMP_CONFIG_FILE}" "${TERMINATOR_CONFIG_FILE}"
+
+    printf " done.\n"
+}
+
+
 
 # helper function to set a value under the "default" section of terminator's config file
 terminator_set_value_default_profile() {
@@ -28,66 +118,21 @@ terminator_set_value_default_profile() {
     " "${file}"
 }
 
-: ${terminator_bg_color:=${terminal_bg_color}}
-: ${terminator_fg_color:=${terminal_fg_color}}
-: ${terminator_cursos_color:=${selected_fg_color}}
-: ${terminator_palette:=${terminal_palette_black}:${terminal_palette_red}:${terminal_palette_green}:${terminal_palette_yellow}:${terminal_palette_blue}:${terminal_palette_purple}:${terminal_palette_cyan}:${terminal_palette_white}:${terminal_palette_light_black}:${terminal_palette_light_red}:${terminal_palette_light_green}:${terminal_palette_light_yellow}:${terminal_palette_light_blue}:${terminal_palette_light_purple}:${terminal_palette_light_cyan}:${terminal_palette_light_white}}
-: ${terminator_transparency:=${terminal_transparency}}
 
-TERMINATOR_ENABLE_DEFAULT="true"
-TERMINATOR_CONFIG_FILE_DEFAULT="$HOME/.config/terminator/config"
 
-TERMINATOR_ENABLE="$(crudini      --get ${GCS_CONFIG_FILE} terminator enable      2>/dev/null || echo "${TERMINATOR_ENABLE_DEFAULT}")"
-TERMINATOR_CONFIG_FILE="$(crudini --get ${GCS_CONFIG_FILE} terminator config_file 2>/dev/null || echo "${TERMINATOR_CONFIG_FILE_DEFAULT}")"
+terminator_init_module
+terminator_check_dependencies
+[ $? == 1 ] && return
 
-if ! [ "${TERMINATOR_ENABLE}" == "true" ]; then
-    printf "* Ignoting terminator (disabled from configuration).\n"
-
-elif ! [ -f "${TERMINATOR_CONFIG_FILE}" ]; then
-    printf "* Ignoring terminator (configuration file not found: ${TERMINATOR_CONFIG_FILE}).\n"
-
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
-    printf "* Making backup of terminator configuration file..."
-
-    TERMINATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/terminator"
-    mkdir -p "${TERMINATOR_BACKUP_DIR}"
-    cp "${TERMINATOR_CONFIG_FILE}" "${TERMINATOR_BACKUP_DIR}/config"
-
-    printf " done.\n"
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    terminator_create_backup
 
 elif [ "${GCS_ACTION}" == "restore-backup" ]; then
-    printf "* Restoring backup of terminator configuration file..."
-
-    TERMINATOR_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/terminator"
-    if [ -f "${TERMINATOR_BACKUP_DIR}/config" ]; then
-        cp "${TERMINATOR_BACKUP_DIR}/config" "${TERMINATOR_CONFIG_FILE}"
-        printf " done.\n"
-    else
-        printf " not found!\n"
-    fi
+    terminator_restore_backup
 
 elif [ "${GCS_ACTION}" == "apply-theme" ]; then
-    printf "* Setting colors for terminator..."
-
-    TERMINATOR_TMP_DIR="${GCS_TMP_DIR}/terminator"
-    TERMINATOR_TMP_CONFIG_FILE="${TERMINATOR_TMP_DIR}/config"
-    mkdir "${TERMINATOR_TMP_DIR}"
-    cp "${TERMINATOR_CONFIG_FILE}" "${TERMINATOR_TMP_CONFIG_FILE}"
-
-    terminator_set_value_default_profile "background_color" "${terminal_bg_color}"  "${TERMINATOR_TMP_CONFIG_FILE}"
-    terminator_set_value_default_profile "foreground_color" "${terminal_fg_color}"  "${TERMINATOR_TMP_CONFIG_FILE}"
-    terminator_set_value_default_profile "cursor_color"     "${terminal_fg_color}"  "${TERMINATOR_TMP_CONFIG_FILE}"
-    terminator_set_value_default_profile "palette"          "${terminator_palette}" "${TERMINATOR_TMP_CONFIG_FILE}"
-    if [ "${terminal_transparency}" != "" ]; then
-        terminator_set_value_default_profile "background_type"     "transparent"              "${TERMINATOR_TMP_CONFIG_FILE}"
-        terminator_set_value_default_profile "background_darkness" "${terminal_transparency}" "${TERMINATOR_TMP_CONFIG_FILE}"
-    else
-        terminator_set_value_default_profile "background_type"     "solid"                    "${TERMINATOR_TMP_CONFIG_FILE}"
-    fi
-
-    mv "${TERMINATOR_TMP_CONFIG_FILE}" "${TERMINATOR_CONFIG_FILE}"
-
-    printf " done.\n"
+    terminator_derive_colors
+    terminator_apply_theme
 
 fi
 
diff --git a/src/share/modules/vim b/src/share/modules/vim
--- a/src/share/modules/vim
+++ b/src/share/modules/vim
@@ -1,44 +1,64 @@
 #!/bin/bash
 
-which vim>/dev/null || return
+function vim_init_module() {
+    VIM_ENABLE_DEFAULT="true"
+    VIM_CONFIG_FILE_DEFAULT="$HOME/.vimrc"
+    VIM_COLORSCHEME_FILE_DEFAULT="$HOME/.vim/colors/${FULL_COLOR_THEME_NAME}.vim"
 
-: ${vim_normal_fg_color:=${editor_fg}}
-: ${vim_normal_bg_color:=${editor_bg}}
-: ${vim_linenr_fg_color:=${editor_frame_fg}}
-: ${vim_linenr_bg_color:=${editor_frame_bg}}
-: ${vim_white_space_color:=${editor_white_space}}
-: ${vim_current_line_bg:=${editor_current_line_bg}}
-: ${vim_selected_fg:=${editor_selected_fg}}
-: ${vim_selected_bg:=${editor_selected_bg}}
-: ${vim_comment:=${editor_comment}}
-: ${vim_string:=${editor_string}}
-: ${vim_operator:=${editor_operator}}
-: ${vim_keyword:=${editor_keyword}}
-: ${vim_preprocessor:=${editor_preprocessor}}
-: ${vim_identifier:=${editor_variable}}
-: ${vim_type:=${editor_class}}
-: ${vim_character:=${editor_character}}
-: ${vim_number:=${editor_number}}
+    VIM_ENABLE="$(crudini           --get ${GCS_CONFIG_FILE} vim enable           2>/dev/null || echo "${VIM_ENABLE_DEFAULT}")"
+    VIM_CONFIG_FILE="$(crudini      --get ${GCS_CONFIG_FILE} vim config_file      2>/dev/null || echo "${VIM_CONFIG_FILE_DEFAULT}")"
+    VIM_COLORSCHEME_FILE="$(crudini --get ${GCS_CONFIG_FILE} vim colorscheme_file 2>/dev/null || echo "${VIM_COLORSCHEME_FILE_DEFAULT}")"
 
-VIM_ENABLE_DEFAULT="true"
-VIM_CONFIG_FILE_DEFAULT="$HOME/.vimrc"
-VIM_COLORSCHEME_FILE_DEFAULT="$HOME/.vim/colors/${FULL_COLOR_THEME_NAME}.vim"
+    GCS_SYNTAX_FALLBACK_DEFAULT="true"
+    GCS_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} gcs syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK_DEFAULT}")"
+    VIM_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} vim syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK}")"
+}
 
-VIM_ENABLE="$(crudini           --get ${GCS_CONFIG_FILE} vim enable           2>/dev/null || echo "${VIM_ENABLE_DEFAULT}")"
-VIM_CONFIG_FILE="$(crudini      --get ${GCS_CONFIG_FILE} vim config_file      2>/dev/null || echo "${VIM_CONFIG_FILE_DEFAULT}")"
-VIM_COLORSCHEME_FILE="$(crudini --get ${GCS_CONFIG_FILE} vim colorscheme_file 2>/dev/null || echo "${VIM_COLORSCHEME_FILE_DEFAULT}")"
 
-GCS_SYNTAX_FALLBACK_DEFAULT="true"
-GCS_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} gcs syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK_DEFAULT}")"
-VIM_SYNTAX_FALLBACK="$(crudini --get ${GCS_CONFIG_FILE} vim syntax_fallback 2>/dev/null || echo "${GCS_SYNTAX_FALLBACK}")"
 
-if ! [ "${VIM_ENABLE}" == "true" ]; then
-    printf "* Ignoring Vim (disabled from configuration).\n"
+function vim_check_dependencies() {
+    if ! which vim >/dev/null; then
+        return 1
 
-elif ! [ -f "${VIM_CONFIG_FILE}" ]; then
-    printf "* Ignoring Vim (config file \"${VIM_CONFIG_FILE}\" not found).\n"
+    elif ! [ "${VIM_ENABLE}" == "true" ]; then
+        printf "* Ignoring Vim (disabled from configuration).\n"
+        return 1
 
-elif [ "${GCS_ACTION}" == "create-backup" ]; then
+    elif ! [ -f "$VIM_CONFIG_FILE}" ]; then
+        printf "* Ignoring Vim (configuration file ${VIM_CONFIG_FILE} not found).\n"
+        return 1
+
+    else
+        return 0
+
+    fi
+}
+
+
+
+function vim_derive_colors() {
+    : ${vim_normal_fg_color:=${editor_fg}}
+    : ${vim_normal_bg_color:=${editor_bg}}
+    : ${vim_linenr_fg_color:=${editor_frame_fg}}
+    : ${vim_linenr_bg_color:=${editor_frame_bg}}
+    : ${vim_white_space_color:=${editor_white_space}}
+    : ${vim_current_line_bg:=${editor_current_line_bg}}
+    : ${vim_selected_fg:=${editor_selected_fg}}
+    : ${vim_selected_bg:=${editor_selected_bg}}
+    : ${vim_comment:=${editor_comment}}
+    : ${vim_string:=${editor_string}}
+    : ${vim_operator:=${editor_operator}}
+    : ${vim_keyword:=${editor_keyword}}
+    : ${vim_preprocessor:=${editor_preprocessor}}
+    : ${vim_identifier:=${editor_variable}}
+    : ${vim_type:=${editor_class}}
+    : ${vim_character:=${editor_character}}
+    : ${vim_number:=${editor_number}}
+}
+
+
+
+function vim_create_backup() {
     printf "* Making backup of Vim configuration file..."
 
     VIM_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/vim"
@@ -46,8 +66,11 @@ elif [ "${GCS_ACTION}" == "create-backup" ]; then
     cp "${VIM_CONFIG_FILE}" "${VIM_BACKUP_DIR}/vimrc"
 
     printf " done.\n"
+}
 
-elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+
+
+function vim_restore_backup() {
     printf "* Restoring backup of Vim configuration file..."
 
     VIM_BACKUP_DIR="${GCS_BACKUPS_DIR}/${GCS_BACKUP_NAME}/vim"
@@ -62,8 +85,11 @@ elif [ "${GCS_ACTION}" == "restore-backup" ]; then
     else
         printf " not found!\n"
     fi
+}
 
-elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+
+
+function vim_apply_theme() {
     if [ "${editor_syntax_enable}" == "false" ]; then
         if [ "${VIM_SYNTAX_FALLBACK}" == "true" ]; then
             printf "* Setting default colors for Vim GUI..."
@@ -118,6 +144,23 @@ elif [ "${GCS_ACTION}" == "apply-theme" ]; then
         printf " done.\n"
 
     fi
+}
+
+
+
+vim_init_module
+vim_check_dependencies
+[ $? == 1 ] && return
+
+if [ "${GCS_ACTION}" == "create-backup" ]; then
+    vim_create_backup
+
+elif [ "${GCS_ACTION}" == "restore-backup" ]; then
+    vim_restore_backup
+
+elif [ "${GCS_ACTION}" == "apply-theme" ]; then
+    vim_derive_colors
+    vim_apply_theme
 
 fi
 
