Added explicit colors for terminal applications

diff --git a/src/gcs b/src/gcs
--- a/src/gcs
+++ b/src/gcs
@@ -32,9 +32,34 @@ if [ "$#" -ne 1 ]; then
 fi
 COLOR_THEME="$1"
 
+
+# set the value of the key named $KEY (in text file $FILE) equal to $VALUE
+# assuming they are separated by $SEPARATOR
+# warning: do not use for config file with different sections, because
+# if the key does not exist, it will be creted at the end of the last section
+# TODO: keep whitespaces at the beginning of the line
+set_value() {
+    if [ "$#" -ne 4 ]; then
+	echo "Error: set_value() requires 4 arguments!"
+	exit 2
+    fi
+    KEY=$1
+    SEPARATOR=$2
+    VALUE=$3
+    FILE=$4
+    if grep "^[[:space:]]*${KEY}${SEPARATOR}.*" "${FILE}" >/dev/null; then
+	sed -i "s/^[[:space:]]*${KEY}${SEPARATOR}.*/${KEY}${SEPARATOR}${VALUE}/" "${FILE}"
+    else
+	echo "${KEY}${SEPARATOR}${VALUE}" >>"${FILE}"
+    fi
+}
+
+
+
 if [ -f "${THEMES_DIR}/${COLOR_THEME}/colortheme" ]; then
     echo "Applying color theme ${COLOR_THEME}"
     echo
+    # main loop invokes all available modules
     for i in "${MODULES_DIR}/"*; do
 	if [ -x "$i" ]; then
 	    . "${THEMES_DIR}/${COLOR_THEME}/colortheme"
