Replaced tabs with spaces

diff --git a/src/gcs b/src/gcs
--- a/src/gcs
+++ b/src/gcs
@@ -220,17 +220,17 @@ load_color_theme() {
 # if the key does not exist, it will be created at the end of the file
 set_value() {
     if [ "$#" -ne 4 ]; then
-	echo "Error: set_value() requires 4 arguments!"
-	exit 2
+        echo "Error: set_value() requires 4 arguments!"
+        exit 2
     fi
     local KEY=$1
     local SEPARATOR=$2
     local VALUE=$3
     local FILE=$4
     if grep -E "^([[:space:]]*|(.*[[:space:]]+))*${KEY}${SEPARATOR}.*" "${FILE}" >/dev/null; then
-	sed -r -i "s/^([[:space:]]*|(.*[[:space:]]+))*${KEY}${SEPARATOR}.*/$(grep -E "^([[:space:]]*|(.*[[:space:]]+))*${KEY}" "${FILE}" | sed "s/${KEY}.*//")${KEY}${SEPARATOR}${VALUE}/" "${FILE}"
+        sed -r -i "s/^([[:space:]]*|(.*[[:space:]]+))*${KEY}${SEPARATOR}.*/$(grep -E "^([[:space:]]*|(.*[[:space:]]+))*${KEY}" "${FILE}" | sed "s/${KEY}.*//")${KEY}${SEPARATOR}${VALUE}/" "${FILE}"
     else
-	echo "${KEY}${SEPARATOR}${VALUE}" >>"${FILE}"
+        echo "${KEY}${SEPARATOR}${VALUE}" >>"${FILE}"
     fi
 }
 
@@ -239,8 +239,8 @@ set_value() {
 # TODO: define behaviour when $SECTION is not found
 set_value_section() {
     if [ "$#" -ne 5 ]; then
-	echo "Error: set_value_section() requires 5 arguments!"
-	exit 2
+        echo "Error: set_value_section() requires 5 arguments!"
+        exit 2
     fi
     local SECTION=$1
     local KEY=$2
diff --git a/src/share/modules/bash_prompt b/src/share/modules/bash_prompt
--- a/src/share/modules/bash_prompt
+++ b/src/share/modules/bash_prompt
@@ -3,8 +3,8 @@
 bash_set_color(){
     
     if [ "$#" -ne 3 ]; then
-	    echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
-	    exit 2
+        echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
+        exit 2
     fi
     
     local key="$1"
@@ -16,25 +16,25 @@ bash_set_color(){
     local escape_code=
     
     case ${value} in
-	*Black)  color_code=0;;
-	*Red)    color_code=1;;
-	*Green)  color_code=2;;
-	*Yellow) color_code=3;;
-	*Blue)   color_code=4;;
-	*Purple) color_code=5;;
-	*Cyan)   color_code=6;;
-	*White)  color_code=7;;
+        *Black)  color_code=0;;
+        *Red)    color_code=1;;
+        *Green)  color_code=2;;
+        *Yellow) color_code=3;;
+        *Blue)   color_code=4;;
+        *Purple) color_code=5;;
+        *Cyan)   color_code=6;;
+        *White)  color_code=7;;
     esac
     
     case ${value} in
-	*B_*) style_code=1;;
-	*U_*) style_code=4;;
-	*)    style_code=0;;
+        *B_*) style_code=1;;
+        *U_*) style_code=4;;
+        *)    style_code=0;;
     esac
     
     case ${value} in
-	*I_*) intensity_code=9;;
-	*)    intensity_code=3;;
+        *I_*) intensity_code=9;;
+        *)    intensity_code=3;;
     esac
     
     escape_code="\'\\\[\\\\e[${style_code};${intensity_code}${color_code}m\\\]\'"
diff --git a/src/share/modules/mcomix b/src/share/modules/mcomix
--- a/src/share/modules/mcomix
+++ b/src/share/modules/mcomix
@@ -3,8 +3,8 @@
 set_color_mcomix() {
     
     if [ "$#" -ne 3 ]; then
-	    echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
-	    exit 2
+        echo "Error: ${FUNCNAME[0]}() requires 3 arguments!"
+        exit 2
     fi
     
     local key="$1"
@@ -15,16 +15,16 @@ set_color_mcomix() {
     local green="$( expr 257 \* $(printf "%d" 0x${value:3:2}))"
     local blue="$(  expr 257 \* $(printf "%d" 0x${value:5:2}))"
     sed -i "
-	/\"${key}\"/{
-	    : search
-	    /\]/ {
-		b replace
-	    }
-	    N
-	    b search
-	    : replace
-	    s/\"${key}\".*\]/\"${key}\": \[${red},${green},${blue}\]/
-	}
+    /\"${key}\"/{
+        : search
+        /\]/ {
+        b replace
+        }
+        N
+        b search
+        : replace
+        s/\"${key}\".*\]/\"${key}\": \[${red},${green},${blue}\]/
+    }
     " "${file}"
 }
 
